--
-- PostgreSQL database dump
--

\restrict mIlo6xJ2QAFDbsOWQj6NmsJDoo1o2ibxiH7Zes4fH4KN92DUJ0lZNnCdvlSPxjf

-- Dumped from database version 17.11
-- Dumped by pg_dump version 18.4

-- Started on 2026-09-23 09:26:04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 36755)
-- Name: ai_model_registry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ai_model_registry (
    id integer NOT NULL,
    model_id character varying(50) NOT NULL,
    version character varying(20) NOT NULL,
    algorithm character varying(80) NOT NULL,
    target_variable character varying(50) NOT NULL,
    training_samples integer DEFAULT 0 NOT NULL,
    validation_samples integer DEFAULT 0 NOT NULL,
    mae numeric(8,4) DEFAULT 0.0000 NOT NULL,
    rmse numeric(8,4) DEFAULT 0.0000 NOT NULL,
    r2_score numeric(6,4) DEFAULT 0.0000 NOT NULL,
    feature_list_json text NOT NULL,
    hyperparameters_json text,
    weights_json text NOT NULL,
    status character varying(20) DEFAULT 'ColdStart'::character varying NOT NULL,
    deployed_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ai_model_registry_status_check CHECK (((status)::text = ANY (ARRAY[('ColdStart'::character varying)::text, ('Experimental'::character varying)::text, ('Validated'::character varying)::text, ('Deployed'::character varying)::text, ('Deprecated'::character varying)::text])))
);


ALTER TABLE public.ai_model_registry OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 36768)
-- Name: ai_model_registry_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ai_model_registry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_model_registry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 36769)
-- Name: ai_route_candidates_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ai_route_candidates_log (
    id integer NOT NULL,
    log_id character varying(30) NOT NULL,
    candidate_index integer DEFAULT 0 NOT NULL,
    summary_title character varying(200) NOT NULL,
    distance_km numeric(7,2) DEFAULT 0.00 NOT NULL,
    duration_mins integer DEFAULT 0 NOT NULL,
    traffic_duration_mins integer DEFAULT 0 NOT NULL,
    estimated_fuel_l numeric(7,2) DEFAULT 0.00 NOT NULL,
    toll_cost_est numeric(10,2) DEFAULT 0.00 NOT NULL,
    composite_score integer DEFAULT 0 NOT NULL,
    is_selected smallint DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.ai_route_candidates_log OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 36781)
-- Name: ai_route_candidates_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ai_route_candidates_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_route_candidates_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 36782)
-- Name: chart_fuel_monthly; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chart_fuel_monthly (
    id integer NOT NULL,
    month_label character varying(10) NOT NULL,
    expense numeric(12,2) NOT NULL,
    sort_order integer NOT NULL
);


ALTER TABLE public.chart_fuel_monthly OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 36785)
-- Name: chart_fuel_monthly_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chart_fuel_monthly ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chart_fuel_monthly_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 36786)
-- Name: chart_weekly_trips; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chart_weekly_trips (
    id integer NOT NULL,
    day_name character varying(10) NOT NULL,
    trips_completed integer NOT NULL,
    sort_order integer NOT NULL
);


ALTER TABLE public.chart_weekly_trips OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 36789)
-- Name: chart_weekly_trips_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chart_weekly_trips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chart_weekly_trips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 36790)
-- Name: cost_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cost_categories (
    id integer NOT NULL,
    name character varying(120) NOT NULL,
    amount numeric(12,2) NOT NULL,
    pct numeric(5,2) NOT NULL,
    color character varying(20) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.cost_categories OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 36794)
-- Name: cost_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cost_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cost_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 36795)
-- Name: drivers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drivers (
    id character varying(20) NOT NULL,
    user_id integer,
    name character varying(120) NOT NULL,
    emp_id character varying(30) DEFAULT NULL::character varying,
    phone character varying(40) DEFAULT NULL::character varying,
    license_no character varying(40) DEFAULT NULL::character varying,
    license_class character varying(100) DEFAULT NULL::character varying,
    license_expiration date,
    status character varying(30) DEFAULT 'Active'::character varying NOT NULL,
    safety_score integer DEFAULT 95 NOT NULL,
    on_time_rate numeric(5,2) DEFAULT 97.00 NOT NULL,
    fuel_efficiency_score integer DEFAULT 90 NOT NULL,
    rating numeric(3,2) DEFAULT 4.80 NOT NULL,
    trip_count integer DEFAULT 0 NOT NULL,
    completed_trips integer DEFAULT 0 NOT NULL,
    cancelled_trips integer DEFAULT 0 NOT NULL,
    department character varying(150) DEFAULT NULL::character varying,
    hrms_status character varying(200) DEFAULT NULL::character varying
);


ALTER TABLE public.drivers OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 36814)
-- Name: fuel_transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fuel_transactions (
    id character varying(30) NOT NULL,
    vehicle_id character varying(20) NOT NULL,
    driver_id character varying(20) DEFAULT NULL::character varying,
    transaction_date timestamp without time zone NOT NULL,
    fuel_type character varying(30) DEFAULT 'Diesel'::character varying,
    liters numeric(8,2) NOT NULL,
    price_per_liter numeric(8,2) NOT NULL,
    total_cost numeric(12,2) NOT NULL,
    odometer integer,
    station character varying(200) DEFAULT NULL::character varying,
    receipt_no character varying(40) DEFAULT NULL::character varying,
    efficiency character varying(20) DEFAULT NULL::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    trip_id character varying(20)
);


ALTER TABLE public.fuel_transactions OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 36823)
-- Name: maintenance_orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_orders (
    id character varying(30) NOT NULL,
    vehicle_id character varying(20) NOT NULL,
    service_type character varying(200) NOT NULL,
    priority character varying(20) DEFAULT 'Medium'::character varying NOT NULL,
    scheduled_date date NOT NULL,
    status character varying(30) DEFAULT 'Scheduled'::character varying NOT NULL,
    estimated_cost numeric(12,2) DEFAULT NULL::numeric,
    notes text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    source_trip_id character varying(20),
    CONSTRAINT maintenance_orders_priority_check CHECK (((priority)::text = ANY (ARRAY[('Critical'::character varying)::text, ('Medium'::character varying)::text, ('Low'::character varying)::text])))
);


ALTER TABLE public.maintenance_orders OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 36833)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    title character varying(200) NOT NULL,
    body text NOT NULL,
    time_label character varying(60) DEFAULT NULL::character varying,
    type character varying(20) DEFAULT 'info'::character varying NOT NULL,
    category character varying(50) DEFAULT NULL::character varying,
    target character varying(60) DEFAULT NULL::character varying,
    is_read smallint DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id integer
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 36844)
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 36845)
-- Name: password_recovery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_recovery (
    id character(64) NOT NULL,
    user_id integer,
    channel character varying(10) NOT NULL,
    destination character varying(150) NOT NULL,
    purpose character varying(30) DEFAULT 'password_reset'::character varying NOT NULL,
    otp_hash character varying(255) NOT NULL,
    delivery_status character varying(12) DEFAULT 'pending'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    verified boolean DEFAULT false NOT NULL,
    used_at timestamp with time zone,
    reset_token_hash character(64),
    reset_expires_at timestamp with time zone,
    CONSTRAINT password_recovery_attempts_check CHECK (((attempts >= 0) AND (attempts <= 5))),
    CONSTRAINT password_recovery_channel_check CHECK (((channel)::text = ANY (ARRAY[('email'::character varying)::text, ('phone'::character varying)::text]))),
    CONSTRAINT password_recovery_delivery_status_check CHECK (((delivery_status)::text = ANY (ARRAY[('pending'::character varying)::text, ('sent'::character varying)::text, ('failed'::character varying)::text, ('skipped'::character varying)::text]))),
    CONSTRAINT password_recovery_purpose_check CHECK (((purpose)::text = 'password_reset'::text))
);


ALTER TABLE public.password_recovery OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 36859)
-- Name: password_recovery_limits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_recovery_limits (
    bucket character(64) NOT NULL,
    window_started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    hits integer DEFAULT 0 NOT NULL,
    last_requested_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.password_recovery_limits OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 36865)
-- Name: permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissions (
    id integer NOT NULL,
    code character varying(100) NOT NULL,
    name character varying(150) NOT NULL,
    module character varying(100) DEFAULT NULL::character varying
);


ALTER TABLE public.permissions OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 36869)
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 36870)
-- Name: reservations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservations (
    id character varying(30) NOT NULL,
    client_name character varying(150) NOT NULL,
    contact_person character varying(120) DEFAULT NULL::character varying,
    contact_phone character varying(40) DEFAULT NULL::character varying,
    passenger_count integer NOT NULL,
    origin character varying(200) NOT NULL,
    destination character varying(200) NOT NULL,
    departure_date date NOT NULL,
    departure_time character varying(20) DEFAULT NULL::character varying,
    return_date date,
    vehicle_requested character varying(120) DEFAULT NULL::character varying,
    assigned_vehicle_id character varying(20) DEFAULT NULL::character varying,
    assigned_driver_id character varying(20) DEFAULT NULL::character varying,
    status character varying(30) DEFAULT 'Pending'::character varying NOT NULL,
    trip_type character varying(120) DEFAULT NULL::character varying,
    notes text,
    estimated_cost numeric(12,2) DEFAULT NULL::numeric,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    cancellation_type character varying(30),
    cancellation_reason character varying(120),
    cancellation_notes text,
    cancelled_by integer,
    cancelled_at timestamp without time zone,
    cancelled_vehicle_id character varying(20),
    cancelled_driver_id character varying(20)
);


ALTER TABLE public.reservations OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 36885)
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permissions (
    role_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.role_permissions OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 36888)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255) DEFAULT NULL::character varying
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 36892)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 36893)
-- Name: route_alternatives; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.route_alternatives (
    id integer NOT NULL,
    preset_id character varying(30) NOT NULL,
    mode_key character varying(30) NOT NULL,
    title character varying(200) NOT NULL,
    distance character varying(30) NOT NULL,
    duration character varying(30) NOT NULL,
    fuel_estimate character varying(60) NOT NULL,
    toll_estimate character varying(30) DEFAULT NULL::character varying,
    total_trip_cost character varying(40) NOT NULL,
    route_score character varying(20) NOT NULL,
    reason text
);


ALTER TABLE public.route_alternatives OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 36899)
-- Name: route_alternatives_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.route_alternatives ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.route_alternatives_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 36900)
-- Name: route_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.route_history (
    id integer NOT NULL,
    log_id character varying(30) NOT NULL,
    route_title character varying(200) NOT NULL,
    vehicle character varying(120) DEFAULT NULL::character varying,
    vehicle_id character varying(20) DEFAULT NULL::character varying,
    generated_date timestamp without time zone NOT NULL,
    selected_mode character varying(30) DEFAULT NULL::character varying,
    variance_accuracy character varying(40) DEFAULT NULL::character varying,
    model_version character varying(30) DEFAULT 'v0-kinematic'::character varying,
    predicted_duration_mins integer,
    predicted_fuel_liters numeric(7,2) DEFAULT NULL::numeric,
    actual_duration_mins integer,
    actual_fuel_liters numeric(7,2) DEFAULT NULL::numeric,
    variance_pct numeric(8,2) DEFAULT NULL::numeric,
    pre_trip_features_json text,
    created_by integer,
    reservation_id character varying(30),
    trip_id character varying(20),
    origin character varying(200),
    destination character varying(200),
    waypoints_json text,
    route_data_json text,
    navigation_key character varying(64),
    actual_fuel_verified smallint DEFAULT 0 NOT NULL,
    actual_fuel_transaction_id character varying(30),
    CONSTRAINT route_history_actual_fuel_verified_check CHECK ((actual_fuel_verified = ANY (ARRAY[0, 1])))
);


ALTER TABLE public.route_history OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 36915)
-- Name: route_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.route_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.route_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 36916)
-- Name: route_presets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.route_presets (
    id character varying(30) NOT NULL,
    name character varying(200) NOT NULL,
    origin character varying(200) NOT NULL,
    origin_lat numeric(10,6) NOT NULL,
    origin_lng numeric(10,6) NOT NULL,
    destination character varying(200) NOT NULL,
    dest_lat numeric(10,6) NOT NULL,
    dest_lng numeric(10,6) NOT NULL,
    passenger_count integer NOT NULL,
    recommended_vehicle character varying(150) DEFAULT NULL::character varying
);


ALTER TABLE public.route_presets OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 36922)
-- Name: route_waypoints; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.route_waypoints (
    id integer NOT NULL,
    preset_id character varying(30) NOT NULL,
    name character varying(200) NOT NULL,
    lat numeric(10,6) NOT NULL,
    lng numeric(10,6) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.route_waypoints OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 36926)
-- Name: route_waypoints_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.route_waypoints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.route_waypoints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 36927)
-- Name: system_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_settings (
    id integer NOT NULL,
    setting_key character varying(80) NOT NULL,
    setting_value character varying(500) DEFAULT NULL::character varying,
    description character varying(255) DEFAULT NULL::character varying
);


ALTER TABLE public.system_settings OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 36934)
-- Name: system_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.system_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 36935)
-- Name: trip_timeline; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trip_timeline (
    id integer NOT NULL,
    trip_id character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    event_time character varying(60) DEFAULT NULL::character varying,
    completed smallint DEFAULT 0 NOT NULL,
    active_step smallint DEFAULT 0 NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.trip_timeline OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 36942)
-- Name: trip_timeline_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trip_timeline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trip_timeline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 36943)
-- Name: trips; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trips (
    id character varying(20) NOT NULL,
    reservation_id character varying(30) DEFAULT NULL::character varying,
    origin character varying(200) NOT NULL,
    destination character varying(200) NOT NULL,
    waypoints character varying(300) DEFAULT NULL::character varying,
    vehicle_id character varying(20) DEFAULT NULL::character varying,
    driver_id character varying(20) DEFAULT NULL::character varying,
    passengers integer,
    scheduled_departure timestamp without time zone,
    actual_departure timestamp without time zone,
    estimated_arrival timestamp without time zone,
    distance_km numeric(6,1) DEFAULT NULL::numeric,
    status character varying(30) DEFAULT 'Scheduled'::character varying NOT NULL,
    progress_pct integer DEFAULT 0 NOT NULL,
    current_step character varying(120) DEFAULT NULL::character varying,
    fuel_estimate character varying(60) DEFAULT NULL::character varying,
    toll_fee numeric(10,2) DEFAULT NULL::numeric,
    driver_allowance numeric(10,2) DEFAULT NULL::numeric,
    total_cost numeric(12,2) DEFAULT NULL::numeric,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    route_history_id character varying(30),
    actual_arrival timestamp without time zone,
    final_odometer integer,
    vehicle_condition character varying(40),
    completion_notes text,
    navigation_active smallint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_trips_navigation_active CHECK ((navigation_active = ANY (ARRAY[0, 1])))
);


ALTER TABLE public.trips OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 36963)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    emp_id character varying(30) NOT NULL,
    name character varying(120) NOT NULL,
    email character varying(150) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role_id integer NOT NULL,
    department character varying(150) DEFAULT NULL::character varying,
    avatar character varying(500) DEFAULT NULL::character varying,
    status character varying(20) DEFAULT 'Active'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    recovery_email character varying(150),
    recovery_phone character varying(40),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY (ARRAY[('Active'::character varying)::text, ('Inactive'::character varying)::text])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 36973)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 36974)
-- Name: vehicle_cost_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehicle_cost_categories (
    id integer NOT NULL,
    category_name character varying(120) NOT NULL,
    active_units integer NOT NULL,
    monthly_expense numeric(12,2) NOT NULL,
    cost_per_km character varying(20) DEFAULT NULL::character varying,
    sort_order integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.vehicle_cost_categories OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 36979)
-- Name: vehicle_cost_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vehicle_cost_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_cost_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 36980)
-- Name: vehicle_cost_ledger; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehicle_cost_ledger (
    id integer NOT NULL,
    vehicle_id character varying(20) NOT NULL,
    plate_number character varying(20) NOT NULL,
    model character varying(100) NOT NULL,
    fuel_cost numeric(12,2) DEFAULT 0 NOT NULL,
    maintenance_cost numeric(12,2) DEFAULT 0 NOT NULL,
    driver_expense numeric(12,2) DEFAULT 0 NOT NULL,
    total_cost numeric(12,2) DEFAULT 0 NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.vehicle_cost_ledger OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 36988)
-- Name: vehicle_cost_ledger_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vehicle_cost_ledger ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_cost_ledger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 36989)
-- Name: vehicles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehicles (
    id character varying(20) NOT NULL,
    plate_number character varying(20) NOT NULL,
    type character varying(60) NOT NULL,
    brand character varying(60) NOT NULL,
    model character varying(100) NOT NULL,
    year integer NOT NULL,
    capacity integer NOT NULL,
    status character varying(30) DEFAULT 'Available'::character varying NOT NULL,
    assigned_driver_id character varying(20) DEFAULT NULL::character varying,
    fuel_type character varying(30) DEFAULT NULL::character varying,
    fuel_capacity integer,
    current_fuel integer,
    odometer integer,
    maintenance_status character varying(150) DEFAULT NULL::character varying,
    next_maintenance character varying(50) DEFAULT NULL::character varying,
    last_maintenance character varying(50) DEFAULT NULL::character varying,
    location character varying(200) DEFAULT NULL::character varying,
    reg_document character varying(200) DEFAULT NULL::character varying,
    insurance_document character varying(200) DEFAULT NULL::character varying,
    ltfrb_permit character varying(200) DEFAULT NULL::character varying,
    total_trips integer DEFAULT 0 NOT NULL,
    total_km integer DEFAULT 0 NOT NULL,
    avg_fuel_km character varying(20) DEFAULT NULL::character varying,
    operating_cost_km character varying(20) DEFAULT NULL::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.vehicles OWNER TO postgres;

--
-- TOC entry 5208 (class 0 OID 36755)
-- Dependencies: 217
-- Data for Name: ai_model_registry; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ai_model_registry (id, model_id, version, algorithm, target_variable, training_samples, validation_samples, mae, rmse, r2_score, feature_list_json, hyperparameters_json, weights_json, status, deployed_at, created_at) FROM stdin;
\.


--
-- TOC entry 5210 (class 0 OID 36769)
-- Dependencies: 219
-- Data for Name: ai_route_candidates_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ai_route_candidates_log (id, log_id, candidate_index, summary_title, distance_km, duration_mins, traffic_duration_mins, estimated_fuel_l, toll_cost_est, composite_score, is_selected, created_at) FROM stdin;
1	LOG-AIR-009	0	via E5	23.63	41	41	6.63	12.00	70	1	2026-09-20 16:31:19.166232
2	LOG-AIR-009	1	via R-8	15.73	44	44	4.42	2.00	62	0	2026-09-20 16:31:19.166232
3	LOG-AIR-009	2	via Metro Manila Skyway	21.87	46	46	6.14	28.00	50	0	2026-09-20 16:31:19.166232
\.


--
-- TOC entry 5212 (class 0 OID 36782)
-- Dependencies: 221
-- Data for Name: chart_fuel_monthly; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chart_fuel_monthly (id, month_label, expense, sort_order) FROM stdin;
\.


--
-- TOC entry 5214 (class 0 OID 36786)
-- Dependencies: 223
-- Data for Name: chart_weekly_trips; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chart_weekly_trips (id, day_name, trips_completed, sort_order) FROM stdin;
\.


--
-- TOC entry 5216 (class 0 OID 36790)
-- Dependencies: 225
-- Data for Name: cost_categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cost_categories (id, name, amount, pct, color, sort_order) FROM stdin;
\.


--
-- TOC entry 5218 (class 0 OID 36795)
-- Dependencies: 227
-- Data for Name: drivers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.drivers (id, user_id, name, emp_id, phone, license_no, license_class, license_expiration, status, safety_score, on_time_rate, fuel_efficiency_score, rating, trip_count, completed_trips, cancelled_trips, department, hrms_status) FROM stdin;
DRV-101	4	Danilo Santos	EMP-TC-0412	+63 917 555 0192	N01-12-887412	Professional (Class 2, 3)	2028-11-20	Active	0	0.00	0	0.00	1	1	0	Heavy Transport Unit	Synced with HRMS (Full-Time Regular)
DRV-102	\N	Reynaldo Ramos	EMP-TC-0488	+63 920 443 1890	N02-14-663910	Professional (Class 1, 2)	2027-08-14	Active	0	0.00	0	0.00	0	0	0	Executive Tour Unit	Synced with HRMS (Full-Time Regular)
DRV-104	\N	Mark Bautista	EMP-TC-0624	+63 917 882 3410	N03-18-112903	Professional (Class 1, 2)	2029-01-25	Active	0	0.00	0	0.00	0	0	0	VIP Concierge Fleet	Synced with HRMS (Full-Time Regular)
DRV-105	\N	Roberto Chavez	EMP-TC-0570	+63 915 770 2214	N01-13-338910	Professional (Class 1, 2)	2028-06-30	Active	0	0.00	0	0.00	0	0	0	Executive Tour Unit	Synced with HRMS (Full-Time Regular)
DRV-106	\N	Arnel Mendoza	EMP-TC-0550	+63 929 110 8823	N02-16-440192	Professional (Class 1, 2)	2027-12-05	Active	0	0.00	0	0.00	0	0	0	Executive Tour Unit	Synced with HRMS (Full-Time Regular)
DRV-107	\N	Ferdinand Lopez	EMP-TC-0499	+63 916 228 9011	N01-13-771890	Professional (Class 1, 2)	2028-05-18	Active	0	0.00	0	0.00	0	0	0	Charter Group Unit	Synced with HRMS (Full-Time Regular)
DRV-108	\N	Joseph Tan	EMP-TC-0380	+63 917 662 4589	N01-11-229871	Professional (Class 2, 3)	2028-09-12	Active	0	0.00	0	0.00	0	0	0	Heavy Transport Unit	Synced with HRMS (Full-Time Regular)
DRV-109	\N	Miguel Santos	EMP-TC-0640	+63 918 440 7718	N02-12-556701	Professional (Class 1, 2)	2027-10-22	Active	0	0.00	0	0.00	0	0	0	Charter Group Unit	Synced with HRMS (Full-Time Regular)
DRV-110	\N	Liza Marquez	EMP-TC-0671	+63 917 889 1023	N03-09-664512	Professional (Class 1)	2028-02-14	Active	0	0.00	0	0.00	0	0	0	VIP Concierge Fleet	Synced with HRMS (Full-Time Regular)
DRV-111	\N	Ramon Dela Cruz	EMP-TC-0702	+63 920 311 8840	N01-17-120394	Professional (Class 2, 3)	2029-04-01	Active	0	0.00	0	0.00	0	0	0	Heavy Transport Unit	Synced with HRMS (Full-Time Regular)
DRV-112	\N	Dennis Aquino	EMP-TC-0445	+63 919 556 3381	N02-11-908871	Professional (Class 1, 2)	2027-11-30	Active	0	0.00	0	0.00	0	0	0	Executive Tour Unit	Synced with HRMS (Full-Time Regular)
DRV-113	\N	Joel Garcia	EMP-TC-0612	+63 915 662 0041	N01-14-778205	Professional (Class 2, 3)	2028-08-19	Active	0	0.00	0	0.00	0	0	0	Charter Group Unit	Synced with HRMS (Full-Time Regular)
DRV-114	\N	Crispin Reyes	EMP-TC-0690	+63 917 334 5566	N02-15-331002	Professional (Class 1, 2)	2027-09-08	Active	0	0.00	0	0.00	0	0	0	Executive Tour Unit	Synced with HRMS (Full-Time Regular)
DRV-115	\N	Noel Villanueva	EMP-TC-0523	+63 918 772 9145	N01-12-556678	Professional (Class 2, 3)	2028-12-25	Active	0	0.00	0	0.00	0	0	0	Heavy Transport Unit	Synced with HRMS (Full-Time Regular)
DRV-117	\N	Mario Torres	EMP-TC-0715	+63 917 990 2230	N02-18-904412	Professional (Class 2, 3)	2028-07-16	Active	0	0.00	0	0.00	0	0	0	Heavy Transport Unit	Synced with HRMS (Full-Time Regular)
DRV-118	\N	Victor Santos	EMP-TC-0584	+63 915 445 6677	N01-10-667781	Professional (Class 1, 2)	2027-12-09	Active	0	0.00	0	0.00	0	0	0	Executive Tour Unit	Synced with HRMS (Full-Time Regular)
DRV-103	\N	Eduardo Cruz	EMP-TC-0511	+63 918 331 7721	N01-15-990234	Professional (Class 2, 3)	2028-03-09	Active	0	0.00	0	0.00	0	0	0	Charter Group Unit	Synced with HRMS (Full-Time Regular)
DRV-116	\N	Alvin Bautista	EMP-TC-0658	+63 920 118 4477	N03-13-229076	Professional (Class 1, 2)	2029-02-28	Active	0	0.00	0	0.00	0	0	0	Charter Group Unit	Synced with HRMS (Full-Time Regular)
\.


--
-- TOC entry 5219 (class 0 OID 36814)
-- Dependencies: 228
-- Data for Name: fuel_transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fuel_transactions (id, vehicle_id, driver_id, transaction_date, fuel_type, liters, price_per_liter, total_cost, odometer, station, receipt_no, efficiency, created_at, trip_id) FROM stdin;
\.


--
-- TOC entry 5220 (class 0 OID 36823)
-- Dependencies: 229
-- Data for Name: maintenance_orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.maintenance_orders (id, vehicle_id, service_type, priority, scheduled_date, status, estimated_cost, notes, created_at, source_trip_id) FROM stdin;
WO-2026-006	VEH-001	Post-trip vehicle inspection	Medium	2026-09-20	Completed	0.00	XSC	2026-09-20 16:33:30.772838	TRP-011
\.


--
-- TOC entry 5221 (class 0 OID 36833)
-- Dependencies: 230
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, title, body, time_label, type, category, target, is_read, created_at, user_id) FROM stdin;
1	New Trip Assignment	Reservation RES-2026-012 has been assigned to you. Open My Trips for route and schedule details.	Just now	info	Dispatch	driver-trips	1	2026-09-20 16:30:11.167064	4
2	Navigation Started	Trip TRP-011 is now In Transit using route LOG-AIR-009.	Just now	info	Trip	driver-trips	0	2026-09-20 16:31:19.166232	4
3	Trip Completed	Trip TRP-011 has been completed.	Just now	success	Trip	trip-details:TRP-011	0	2026-09-20 16:33:30.772838	\N
\.


--
-- TOC entry 5223 (class 0 OID 36845)
-- Dependencies: 232
-- Data for Name: password_recovery; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_recovery (id, user_id, channel, destination, purpose, otp_hash, delivery_status, created_at, expires_at, attempts, verified, used_at, reset_token_hash, reset_expires_at) FROM stdin;
059fbbf07d08da06397bf4bd07fecd41393f3c2a5b86800fa86d969fd58df98f	\N	email	recovery-browser-check@example.invalid	password_reset	$2y$10$xgD1ZyLOP8kBgD5V1aSe0OcGrKS2/0M1mkozVkdk4NXhu.HHPgCwS	skipped	2026-09-13 18:41:08.576149+08	2026-09-13 18:46:08.598957+08	0	f	\N	\N	\N
5eb874ed80a9ecf7ea0f36d45d5f416c2ba9e3210b41b0aadb1021775f59f949	4	email	leidomingo12@gmail.com	password_reset	$2y$10$OBBz5ACAbVKK5s4H4PI1.euNA9ZIH.NE0d6b/x8QqytrQ3BvO9ypO	sent	2026-09-13 19:03:09.850616+08	2026-09-13 19:11:30.497595+08	1	f	\N	\N	\N
7a11f24bdd306b27e2198f564cb73ca297d787220f1168568fd47187887fcb5d	1	email	gowatzilei@gmail.com	password_reset	$2y$10$P4onoy1DJve/mfL5VDt6neX8fyThFdsL7aAvt6Wi7xVMlFYBuATKe	sent	2026-09-13 19:05:55.564487+08	2026-09-13 19:11:38.19202+08	0	f	2026-09-13 19:17:32.823864+08	\N	\N
2f26714b7d00e8357b5825883c2d80206d5e5ade8a74f9ca700c9e95ce6992fb	1	email	gowatzilei@gmail.com	password_reset	$2y$10$BGkZaFkSZVDnt33ru42bmO.t3j2ngC/3Lu0qrdrcwenxMPK1ulMcW	pending	2026-09-13 19:17:32.761364+08	2026-09-13 19:22:32.829598+08	0	f	2026-09-13 19:18:31.154284+08	\N	\N
7414083662f14391e9218d38abce051d2247375b45e114945e0c87b4a4458f8f	1	email	gowatzilei@gmail.com	password_reset	$2y$10$.6HzP.W9.q7q0rhhGC3Fz.ggsnd9xemHO2fZV.Dir9lvorqqxaBQW	failed	2026-09-14 13:23:29.603878+08	2026-09-14 13:28:29.645656+08	0	f	2026-09-14 13:24:02.482794+08	\N	\N
b2ccb962c8197d54a0e7918643c1ffa7b6eb6d6bffe25509a6de84d0420d9bc6	1	email	gowatzilei@gmail.com	password_reset		sent	2026-09-13 19:18:31.122417+08	2026-09-13 19:25:53.346866+08	1	t	2026-09-13 19:21:55.379524+08	\N	2026-09-13 19:31:32.899963+08
5f5ed3215eec82c684714b1b3dc3f072ecb8236f236a436b42e6fb29ce1f79f7	1	email	gowatzilei@gmail.com	password_reset	$2y$10$1Xu26sdaPmcaTNlaHXMxFeuB3Kzcegdd8BbcbivEs/aT7mglW9UTW	pending	2026-09-13 19:21:55.349578+08	2026-09-13 19:26:55.380925+08	0	f	2026-09-13 19:25:16.459666+08	\N	\N
26c8466ac709527731f0e66e5269b98f67264cca3ba39546c2381a61ebd00409	1	email	gowatzilei@gmail.com	password_reset	$2y$10$.zqig/gRMDLobkLLvUVgnefQzC5YeIQbRE8H2ZeP0C8bJerdhaxh6	sent	2026-09-14 13:28:38.877155+08	2026-09-14 13:33:59.182519+08	0	f	2026-09-14 13:32:29.508498+08	\N	\N
854cebd9071da67faed019f74ccbe54ea259ad355e140490b3b9f3e59be04a2f	1	email	gowatzilei@gmail.com	password_reset		sent	2026-09-13 19:25:16.431955+08	2026-09-13 19:30:22.086631+08	1	t	2026-09-13 19:52:43.02171+08	\N	2026-09-13 19:35:39.170127+08
bf77ecd824ae0f2e58d579a885d03d3499bc501fda66952f53c191c378720548	1	email	gowatzilei@gmail.com	password_reset	$2y$10$7Zj5DDdU/WOzmKxGKDZ9eeR9QzTYrOlWxm/pPPuQwnm29JuAAVM6G	pending	2026-09-13 19:52:42.954384+08	2026-09-13 19:57:43.025532+08	0	f	2026-09-13 19:55:36.937609+08	\N	\N
4b40e3887be7a0230c98a5f044efacb161c38cb3b2db2bf7e410415ea46fae83	1	email	gowatzilei@gmail.com	password_reset	$2y$10$sdSRoho0GDh8oPltu.Rp5O6V5ezraKTq.ukS9Oz2F4Aw0z//eojv2	pending	2026-09-13 19:55:36.905786+08	2026-09-13 20:00:36.939286+08	0	f	2026-09-13 20:01:01.179396+08	\N	\N
2fe41e3942875519a50b74537780b41e918878b1bf62e5299efd1627aa9fd696	1	email	gowatzilei@gmail.com	password_reset	$2y$10$KpJSLc.uCgOCsf0ZXnXEYOs2Hv5E35NKEiT94xAw5WHDNuyc7kh2S	pending	2026-09-13 20:01:01.149257+08	2026-09-13 20:06:01.180899+08	0	f	2026-09-13 20:03:53.385411+08	\N	\N
7160ec0ce0b45df130a149f0bb245d96fc2b9d82978a781ca6d51423767f232d	1	email	gowatzilei@gmail.com	password_reset	$2y$10$ZA9z6W7AdOB8XeqiGm2GjO2vzKLpfCfmVUPhGBrq3d1DphnaAYxAu	pending	2026-09-13 20:03:53.356519+08	2026-09-13 20:08:53.38679+08	0	f	2026-09-13 20:06:53.666615+08	\N	\N
8070ad8ba5019b7ad00af912dde2f2b92b6134b675f839b1b30be270430e8588	1	email	gowatzilei@gmail.com	password_reset	$2y$10$sF0/w.WWt9UpaOrb6BHFAuxujDj5oc5o0p8HdFxhhVl3DuM8/AOWq	pending	2026-09-13 20:06:53.633626+08	2026-09-13 20:11:53.668289+08	0	f	2026-09-14 13:23:29.643403+08	\N	\N
068d8710975f9874230914587be78ea1b3cf343be12ad1d41bf1f86e0d15efe8	1	email	gowatzilei@gmail.com	password_reset	$2y$10$ZmtbrxdBDKPKdLc4oHYOhu0IJ4uu2bLbMYdDkr3onmanc0NCyCGGK	sent	2026-09-14 13:32:29.495349+08	2026-09-14 13:37:42.308281+08	0	f	2026-09-14 14:23:58.554628+08	\N	\N
e5f88926fe724d1e13858c2e347c3a14b1f1ee2a143a11456d49821c5eb4c740	1	email	gowatzilei@gmail.com	password_reset		sent	2026-09-14 14:23:58.529159+08	2026-09-14 14:29:03.90618+08	1	t	\N	4d3ba3926473ca4994e5c61a577a9565aa04e050ca7a9fa0fb23cf4b9f32c537	2026-09-14 14:34:31.933714+08
\.


--
-- TOC entry 5224 (class 0 OID 36859)
-- Dependencies: 233
-- Data for Name: password_recovery_limits; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_recovery_limits (bucket, window_started_at, hits, last_requested_at) FROM stdin;
9dd543cd9e2edba8a044ab3566ed52a4769f4be10c7f1524f18e3d7efc9bde4c	2026-09-13 18:41:08.576149+08	1	2026-09-13 18:41:08.587764+08
35612322820cafaa6d65ad05fd8d7482e939fde1020d0d58dab9678987bce6d3	2026-09-13 19:03:09.850616+08	1	2026-09-13 19:03:09.876363+08
b8633b0bbb5585ed154b1c453e8a36f2b7977597d77b5654f972fa313aea5bd6	2026-09-13 19:05:55.564487+08	1	2026-09-13 19:05:55.574674+08
ac8fd52d06567f2bd4c8b8419ac51fcaeb94ba2c154d6d5521afa29a654de438	2026-09-13 19:17:32.761364+08	1	2026-09-13 19:17:32.800554+08
700267b9f8db9dab934bd26b1baa837b50fafc07281b140d9807764a23615af2	2026-09-13 19:17:32.761364+08	1	2026-09-13 19:17:32.804072+08
940ce2531ac1be9d55342f693bcf6d8b48b162e63a79be76d68745e74395b72f	2026-09-13 19:52:42.954384+08	1	2026-09-13 19:52:42.991213+08
90be9e9c66871257854920ffd47ad8328199113a363b6c8fe0376bd0cf2fe374	2026-09-13 19:55:36.905786+08	1	2026-09-13 19:55:36.915624+08
f3a97849e07eb2f2b1fc4de26395f63ef87a45117df2e6d9b69f34c1f9771ac7	2026-09-14 13:23:29.632436+08	1	2026-09-14 13:23:29.63319+08
ff10143192614448ce01dd383681f51c032c2b5e78784c3cf4d4513bc9aab385	2026-09-14 13:28:14.499103+08	2	2026-09-14 14:23:40.82391+08
f9f952e3dde53056c545e9be889d99f66427f9c65e4e1030c96a104f4b0f3301	2026-09-14 14:23:58.535959+08	1	2026-09-14 14:23:58.537444+08
0d3954c172ad66e4cded82dcdacfec5d003cdd8bc338a41e230a99766f46fcfe	2026-09-14 13:28:38.881195+08	3	2026-09-14 14:23:58.539889+08
8fca4523b8b093d64850fb1b4e628ab9e4e263c8603677018cd475fbcb5675ce	2026-09-14 14:24:31.784641+08	1	2026-09-14 14:24:31.785537+08
\.


--
-- TOC entry 5225 (class 0 OID 36865)
-- Dependencies: 234
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.permissions (id, code, name, module) FROM stdin;
1	vehicles.view	View Vehicle Directory	Fleet & Vehicle Management
2	vehicles.assign	Assign Vehicles & Drivers	Fleet & Vehicle Management
3	vehicles.manage	Manage Vehicle Records (CRUD)	Fleet & Vehicle Management
4	dispatch.view	View Reservations & Dispatch	Reservation & Dispatch
5	dispatch.manage	Manage Dispatch Workflow	Reservation & Dispatch
6	drivers.view	View Driver Performance	Driver & Trip Performance
7	fuel.view	View Fuel Management	Fuel Management
8	fuel.manage	Manage Fuel Transactions	Fuel Management
9	costs.view	View Cost Analysis	Cost Analysis (TCAO)
10	costs.manage	Manage Cost Configuration	Cost Analysis (TCAO)
11	ai.view	View AI Route Optimization	AI Route Optimization
12	ai.manage	Manage AI Route Generation	AI Route Optimization
13	reports.view	View & Generate Reports	System
14	settings.manage	Manage System Settings & RBAC	System
15	notifications.view	View Notifications Center	System
16	driver.portal	Access Driver Portal	Driver Portal
17	ai.navigate	Navigate Assigned Route	AI Route Optimization
\.


--
-- TOC entry 5227 (class 0 OID 36870)
-- Dependencies: 236
-- Data for Name: reservations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reservations (id, client_name, contact_person, contact_phone, passenger_count, origin, destination, departure_date, departure_time, return_date, vehicle_requested, assigned_vehicle_id, assigned_driver_id, status, trip_type, notes, estimated_cost, created_at, cancellation_type, cancellation_reason, cancellation_notes, cancelled_by, cancelled_at, cancelled_vehicle_id, cancelled_driver_id) FROM stdin;
RES-2026-012	ZENNA FAMILY	12345678	12345678912	25	4128 Rose Lane, Quezon City	1225 Roxas Boulevard Manila Metro Manila	2026-09-22	05:00 AM	2026-09-22	Tour Bus (45-50 pax)	VEH-001	DRV-101	Completed	Day Tour & Transfer	EEDE	10000.00	2026-09-20 16:30:04.881938	\N	\N	\N	\N	\N	\N	\N
\.


--
-- TOC entry 5228 (class 0 OID 36885)
-- Dependencies: 237
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role_permissions (role_id, permission_id) FROM stdin;
1	1
1	2
1	3
1	4
1	5
1	6
1	7
1	8
1	9
1	10
1	11
1	12
1	13
1	14
1	15
1	16
2	1
2	2
2	3
2	4
2	6
2	7
2	8
2	9
2	10
2	11
2	12
2	13
2	15
3	1
3	2
3	4
3	5
3	6
3	7
3	9
3	11
3	12
3	13
3	15
4	7
4	8
4	11
4	15
4	16
1	17
2	17
3	17
4	17
\.


--
-- TOC entry 5229 (class 0 OID 36888)
-- Dependencies: 238
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, code, name, description) FROM stdin;
1	fleet_admin	Fleet Administrator	Full console access to every module and system settings.
2	fleet_manager	Fleet Manager	Vehicle, cost and AI route management; dispatch view-only.
3	dispatcher	Dispatcher	Reservation and dispatch workflow; cost view-only.
4	driver	Driver	Driver portal: own trips, assigned vehicle and route info.
\.


--
-- TOC entry 5231 (class 0 OID 36893)
-- Dependencies: 240
-- Data for Name: route_alternatives; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.route_alternatives (id, preset_id, mode_key, title, distance, duration, fuel_estimate, toll_estimate, total_trip_cost, route_score, reason) FROM stdin;
\.


--
-- TOC entry 5233 (class 0 OID 36900)
-- Dependencies: 242
-- Data for Name: route_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.route_history (id, log_id, route_title, vehicle, vehicle_id, generated_date, selected_mode, variance_accuracy, model_version, predicted_duration_mins, predicted_fuel_liters, actual_duration_mins, actual_fuel_liters, variance_pct, pre_trip_features_json, created_by, reservation_id, trip_id, origin, destination, waypoints_json, route_data_json, navigation_key, actual_fuel_verified, actual_fuel_transaction_id) FROM stdin;
1	LOG-AIR-009	4128 Rose Lane, Quezon City to 1225 Roxas Boulevard Manila Metro Manila	Hino Grand View 45s (NBO-7821)	VEH-001	2026-09-20 16:31:19.166232	Fastest Express Corridor	70 / 100 Score	v0-kinematic	41	6.63	1	\N	97.91	{"distance_km":23.63,"base_duration_mins":41,"traffic_delay_ratio":1,"waypoint_count":0,"baseline_km_per_liter":3.8,"vehicle_weight_class":3,"passenger_load_ratio":0.556,"highway_ratio":0.139}	4	RES-2026-012	TRP-011	4128 Rose Lane, Quezon City	1225 Roxas Boulevard Manila Metro Manila	[]	{"mode":"fastest","route":{"title":"ROUTETHINK: Fastest Express Corridor","distance":"23.6 km","distanceKm":23.63,"duration":"41 mins","durationMins":41,"fuelEstimate":"6.6 L (₱387)","fuelEstimateLiters":6.63,"tollEstimate":"₱12","totalTripCost":"₱399","routeScore":"70 / 100","reason":"Selected via E5: Saves approximately 3 mins (6.8% faster) transit time compared to via R-8 by prioritizing high-capacity expressway corridors.","modelVersion":"v0-kinematic","isMlActive":false,"isFullyMlActive":false,"fuelModelVersion":null,"durationModelVersion":null,"legs":[{"from":"4128 Rose St","to":"1225 Roxas Blvd","distance":"23.6 km","distanceMeters":23630,"duration":"41 mins","durationSeconds":2432,"durationInTraffic":"41 mins","durationInTrafficSeconds":2432}],"candidates":[{"index":0,"summary":"via E5","distanceKm":23.63,"exactDistanceMeters":23630,"exactDurationSecs":2432,"exactFuelScore":6.218421052631579,"durationMins":41,"baseDurationMins":41,"trafficDurationMins":41,"trafficDelayRatio":1,"fuelEstimateLiters":6.63,"fuelCost":387,"tollEstimate":12,"totalTripCost":399,"isMlPredicted":false,"isFuelMlPredicted":false,"isDurationMlPredicted":false,"isFullyMlActive":false,"fuelModelVersion":null,"durationModelVersion":null,"modelVersion":"v0-kinematic","rawRoute":{"index":0,"summary":"via E5","distanceMeters":23630,"distanceKm":23.63,"durationSecs":2432,"durationMins":41,"baseDurationMins":41,"trafficDurationMins":41,"trafficDelayRatio":1,"highwayRatio":0.139,"legs":[{"from":"4128 Rose St","to":"1225 Roxas Blvd","distance":"23.6 km","distanceMeters":23630,"duration":"41 mins","durationSeconds":2432,"durationInTraffic":"41 mins","durationInTrafficSeconds":2432}]},"features":{"distance_km":23.63,"base_duration_mins":41,"traffic_delay_ratio":1,"waypoint_count":0,"baseline_km_per_liter":3.8,"vehicle_weight_class":3,"passenger_load_ratio":0.556,"highway_ratio":0.139},"compositeScore":70,"durationFormatted":"41 mins","distanceFormatted":"23.6 km","fuelFormatted":"6.6 L","costFormatted":"₱399","tollFormatted":"₱12"},{"index":1,"summary":"via R-8","distanceKm":15.73,"exactDistanceMeters":15726,"exactDurationSecs":2618,"exactFuelScore":4.138421052631579,"durationMins":44,"baseDurationMins":44,"trafficDurationMins":44,"trafficDelayRatio":1,"fuelEstimateLiters":4.42,"fuelCost":258,"tollEstimate":2,"totalTripCost":260,"isMlPredicted":false,"isFuelMlPredicted":false,"isDurationMlPredicted":false,"isFullyMlActive":false,"fuelModelVersion":null,"durationModelVersion":null,"modelVersion":"v0-kinematic","rawRoute":{"index":1,"summary":"via R-8","distanceMeters":15726,"distanceKm":15.73,"durationSecs":2618,"durationMins":44,"baseDurationMins":44,"trafficDurationMins":44,"trafficDelayRatio":1,"highwayRatio":0.027,"legs":[{"from":"4128 Rose St","to":"1225 Roxas Blvd","distance":"15.7 km","distanceMeters":15726,"duration":"44 mins","durationSeconds":2618,"durationInTraffic":"44 mins","durationInTrafficSeconds":2618}]},"features":{"distance_km":15.73,"base_duration_mins":44,"traffic_delay_ratio":1,"waypoint_count":0,"baseline_km_per_liter":3.8,"vehicle_weight_class":3,"passenger_load_ratio":0.556,"highway_ratio":0.027},"compositeScore":62,"durationFormatted":"44 mins","distanceFormatted":"15.7 km","fuelFormatted":"4.4 L","costFormatted":"₱260","tollFormatted":"₱2"},{"index":2,"summary":"via Metro Manila Skyway","distanceKm":21.87,"exactDistanceMeters":21872,"exactDurationSecs":2776,"exactFuelScore":5.755789473684211,"durationMins":46,"baseDurationMins":46,"trafficDurationMins":46,"trafficDelayRatio":1,"fuelEstimateLiters":6.14,"fuelCost":359,"tollEstimate":28,"totalTripCost":387,"isMlPredicted":false,"isFuelMlPredicted":false,"isDurationMlPredicted":false,"isFullyMlActive":false,"fuelModelVersion":null,"durationModelVersion":null,"modelVersion":"v0-kinematic","rawRoute":{"index":2,"summary":"via Metro Manila Skyway","distanceMeters":21872,"distanceKm":21.87,"durationSecs":2776,"durationMins":46,"baseDurationMins":46,"trafficDurationMins":46,"trafficDelayRatio":1,"highwayRatio":0.34,"legs":[{"from":"4128 Rose St","to":"1225 Roxas Blvd","distance":"21.9 km","distanceMeters":21872,"duration":"46 mins","durationSeconds":2776,"durationInTraffic":"46 mins","durationInTrafficSeconds":2776}]},"features":{"distance_km":21.87,"base_duration_mins":46,"traffic_delay_ratio":1,"waypoint_count":0,"baseline_km_per_liter":3.8,"vehicle_weight_class":3,"passenger_load_ratio":0.556,"highway_ratio":0.34},"compositeScore":50,"durationFormatted":"46 mins","distanceFormatted":"21.9 km","fuelFormatted":"6.1 L","costFormatted":"₱387","tollFormatted":"₱28"}]},"selectedCandidate":{"index":0,"summary":"via E5","distanceKm":23.63,"exactDistanceMeters":23630,"exactDurationSecs":2432,"exactFuelScore":6.218421052631579,"durationMins":41,"baseDurationMins":41,"trafficDurationMins":41,"trafficDelayRatio":1,"fuelEstimateLiters":6.63,"fuelCost":387,"tollEstimate":12,"totalTripCost":399,"isMlPredicted":false,"isFuelMlPredicted":false,"isDurationMlPredicted":false,"isFullyMlActive":false,"fuelModelVersion":null,"durationModelVersion":null,"modelVersion":"v0-kinematic","rawRoute":{"index":0,"summary":"via E5","distanceMeters":23630,"distanceKm":23.63,"durationSecs":2432,"durationMins":41,"baseDurationMins":41,"trafficDurationMins":41,"trafficDelayRatio":1,"highwayRatio":0.139,"legs":[{"from":"4128 Rose St","to":"1225 Roxas Blvd","distance":"23.6 km","distanceMeters":23630,"duration":"41 mins","durationSeconds":2432,"durationInTraffic":"41 mins","durationInTrafficSeconds":2432}]},"features":{"distance_km":23.63,"base_duration_mins":41,"traffic_delay_ratio":1,"waypoint_count":0,"baseline_km_per_liter":3.8,"vehicle_weight_class":3,"passenger_load_ratio":0.556,"highway_ratio":0.139},"compositeScore":70,"durationFormatted":"41 mins","distanceFormatted":"23.6 km","fuelFormatted":"6.6 L","costFormatted":"₱399","tollFormatted":"₱12"}}	f7426d4ea42ad5f79daf6d034becb114bd1a8bb0714f0ce348d1708eb49d9aa8	0	\N
\.


--
-- TOC entry 5235 (class 0 OID 36916)
-- Dependencies: 244
-- Data for Name: route_presets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.route_presets (id, name, origin, origin_lat, origin_lng, destination, dest_lat, dest_lng, passenger_count, recommended_vehicle) FROM stdin;
\.


--
-- TOC entry 5236 (class 0 OID 36922)
-- Dependencies: 245
-- Data for Name: route_waypoints; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.route_waypoints (id, preset_id, name, lat, lng, sort_order) FROM stdin;
\.


--
-- TOC entry 5238 (class 0 OID 36927)
-- Dependencies: 247
-- Data for Name: system_settings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.system_settings (id, setting_key, setting_value, description) FROM stdin;
2	system.title	Toursphere Fleet & Transportation Management	Application display title
3	system.version	2.4.0	System version
4	integration.booking_core	Connected	Travel & Tours Main Booking Core - synchronizes incoming reservation queues
5	integration.hrms	Connected	Toursphere HRMS Module - employee records, driver payroll, shift attendance
6	integration.gps_gateway	Active	Mapping & GPS Telematics API Gateway - OpenStreetMap & Leaflet vector layer
7	cost.monthly_total	1428650.00	Monthly total operating cost (PHP)
8	cost.monthly_budget	1650000.00	Monthly operational budget (PHP)
9	ai.recommendation_1	Route Rationalization Savings|Using Module 6 AI Route Planning saved approximately ₱42,300 in unnecessary diesel idling on NLEX routes.	AI cost optimization recommendation #1
10	ai.recommendation_2	Driver Efficiency Reward|Danilo Santos and Mark Bautista achieved >95% fuel score, yielding 8% lower consumption vs fleet baseline.	AI cost optimization recommendation #2
11	ai.recommendation_3	Fleet PMS Predictor|Timely preventative maintenance on Grand View Coach avoided estimated ₱90k unplanned gearbox repairs.	AI cost optimization recommendation #3
41	company.timezone	Asia/Manila	\N
42	company.currency	PHP	\N
1	system.brand	Toursphere	Application brand name
38	company.email		\N
39	company.phone		\N
40	company.address		\N
24	sequence.fuel_transactions.id.fl-2026	4	Persistent sequential ID counter
12	sequence.reservations.id.res-2026	12	Persistent sequential ID counter
13	sequence.trips.id.trp	11	Persistent sequential ID counter
14	sequence.route_history.log_id.log-air	9	Persistent sequential ID counter
25	sequence.maintenance_orders.id.wo-2026	6	Persistent sequential ID counter
26	user.1.theme	light	\N
\.


--
-- TOC entry 5240 (class 0 OID 36935)
-- Dependencies: 249
-- Data for Name: trip_timeline; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trip_timeline (id, trip_id, title, event_time, completed, active_step, sort_order) FROM stdin;
1	TRP-011	Navigation Started	2026-09-20 16:31	1	0	1
2	TRP-011	Returning to Depot	2026-09-20 16:32	0	0	2
3	TRP-011	Trip Completed	2026-09-20 16:33	1	0	3
\.


--
-- TOC entry 5242 (class 0 OID 36943)
-- Dependencies: 251
-- Data for Name: trips; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trips (id, reservation_id, origin, destination, waypoints, vehicle_id, driver_id, passengers, scheduled_departure, actual_departure, estimated_arrival, distance_km, status, progress_pct, current_step, fuel_estimate, toll_fee, driver_allowance, total_cost, created_at, route_history_id, actual_arrival, final_odometer, vehicle_condition, completion_notes, navigation_active) FROM stdin;
TRP-011	RES-2026-012	4128 Rose Lane, Quezon City	1225 Roxas Boulevard Manila Metro Manila		VEH-001	DRV-101	25	2026-09-22 05:00:00	2026-09-20 16:31:19.166232	\N	23.6	Completed	100	Completed & Returned	\N	40.00	\N	\N	2026-09-20 16:30:11.167064	LOG-AIR-009	2026-09-20 16:33:30.772838	42000	Needs Inspection	XSC	0
\.


--
-- TOC entry 5243 (class 0 OID 36963)
-- Dependencies: 252
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, emp_id, name, email, password_hash, role_id, department, avatar, status, created_at, recovery_email, recovery_phone) FROM stdin;
2	EMP-TC-7601	Patricia Lim	manager.fleet@toursphere.com	$2y$10$966WZewSGNy1wR3zQxSHeeknXWlggbvblFmWP2WOzlACodEactjsi	2	Fleet Operations & Logistics	https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80	Active	2026-08-27 13:14:52.392358	\N	\N
3	EMP-TC-5320	Kevin Torres	dispatch.ops@toursphere.com	$2y$10$966WZewSGNy1wR3zQxSHeeknXWlggbvblFmWP2WOzlACodEactjsi	3	Dispatch & Reservations	https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80	Active	2026-08-27 13:14:52.392358	\N	\N
4	EMP-TC-0412	Danilo Santos	d.santos@toursphere.com	$2y$10$966WZewSGNy1wR3zQxSHeeknXWlggbvblFmWP2WOzlACodEactjsi	4	Heavy Transport Unit	https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=120&auto=format&fit=crop&q=80	Active	2026-08-27 13:14:52.392358	leidomingo12@gmail.com	\N
1	EMP-TC-8802	Alex Ramirez	a.ramirez@toursphere.com	$2y$10$966WZewSGNy1wR3zQxSHeeknXWlggbvblFmWP2WOzlACodEactjsi	1	Fleet Operations & Logistics	https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80	Active	2026-08-27 13:14:52.392358	gowatzilei@gmail.com	09817932956
\.


--
-- TOC entry 5245 (class 0 OID 36974)
-- Dependencies: 254
-- Data for Name: vehicle_cost_categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vehicle_cost_categories (id, category_name, active_units, monthly_expense, cost_per_km, sort_order) FROM stdin;
\.


--
-- TOC entry 5247 (class 0 OID 36980)
-- Dependencies: 256
-- Data for Name: vehicle_cost_ledger; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vehicle_cost_ledger (id, vehicle_id, plate_number, model, fuel_cost, maintenance_cost, driver_expense, total_cost, sort_order) FROM stdin;
\.


--
-- TOC entry 5249 (class 0 OID 36989)
-- Dependencies: 258
-- Data for Name: vehicles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vehicles (id, plate_number, type, brand, model, year, capacity, status, assigned_driver_id, fuel_type, fuel_capacity, current_fuel, odometer, maintenance_status, next_maintenance, last_maintenance, location, reg_document, insurance_document, ltfrb_permit, total_trips, total_km, avg_fuel_km, operating_cost_km, created_at) FROM stdin;
VEH-004	WOD-3312	VIP SUV	Ford	Everest Titanium 4x4	2024	7	Available	\N	Diesel	80	0	0	Healthy	2026-11-15	2026-08-01	\N	OR/CR Valid until 2027-06-30	Malayan VIP Coverage - Exp 2027-06-01	CPC No. 2024-99812	0	0	10.5 km/L	₱11.20/km	2026-08-27 13:14:52.392358
VEH-008	UAD-9043	Tour Bus	Volvo	B8R Coach 50s	2023	50	Available	\N	Diesel	280	0	0	Healthy	2026-09-30	2026-07-02	\N	OR/CR Valid until 2027-08-19	QBE Heavy Fleet - Exp 2027-07-15	CPC No. 2023-66710	0	0	3.7 km/L	₱23.20/km	2026-08-27 13:14:52.392358
VEH-009	TGT-1201	Tour Bus	Yutong	ZK6122H9 Coach	2022	49	Available	\N	Diesel	300	0	0	Healthy	2026-10-08	2026-07-15	\N	OR/CR Valid until 2027-03-11	QBE Heavy Fleet - Exp 2026-12-30	CPC No. 2023-22109	0	0	3.6 km/L	₱23.80/km	2026-08-27 13:14:52.392358
VEH-018	FGH-1042	Executive Van	Toyota	HiAce Tourer	2022	14	Available	\N	Diesel	70	0	0	Healthy	2026-10-30	2026-07-25	\N	OR/CR Valid until 2027-03-19	Standard Charter - Exp 2027-03-01	CPC No. 2023-55690	0	0	9.1 km/L	₱12.40/km	2026-08-27 13:14:52.392358
VEH-014	HJK-6619	Coaster Bus	Hyundai	County Deluxe	2022	29	Available	\N	Diesel	95	0	0	Healthy	2026-10-11	2026-07-22	\N	OR/CR Valid until 2027-04-03	Pioneer Charter - Exp 2027-03-10	CPC No. 2023-77812	0	0	6.5 km/L	₱16.10/km	2026-08-27 13:14:52.392358
VEH-010	KJS-2210	Coaster Bus	Toyota	Coaster Commuter	2022	29	Available	\N	Diesel	95	100	49000	Needs Inspection after trip	2026-11-02	2026-08-30	\N	OR/CR Valid until 2027-01-22	Pioneer Charter - Exp 2027-01-05	CPC No. 2023-55820	0	0	6.6 km/L	₱15.90/km	2026-08-27 13:14:52.392358
VEH-002	CAV-4519	Executive Van	Toyota	HiAce Grandia Tourer	2024	14	Available	\N	Diesel	70	0	0	Healthy	2026-10-02	2026-07-05	\N	OR/CR Valid until 2027-04-10	Standard Charter - Exp 2027-03-22	CPC No. 2024-11045	0	0	9.2 km/L	₱12.80/km	2026-08-27 13:14:52.392358
VEH-025	LKO-8710	Coaster Bus	Isuzu	NPR Coaster	2021	28	Available	\N	Diesel	90	0	0	Healthy	2026-11-01	2026-08-03	\N	OR/CR Valid until 2026-12-28	Pioneer Charter - Exp 2026-12-12	CPC No. 2022-66708	0	0	6.1 km/L	₱16.60/km	2026-08-27 13:14:52.392358
VEH-026	IJU-9821	Executive Van	Mercedes	Vito Tourer	2024	8	Available	\N	Diesel	66	0	0	Healthy	2026-12-20	2026-08-15	\N	OR/CR Valid until 2027-09-01	Alpha Insurance - Exp 2027-08-20	CPC No. 2024-11230	0	0	10.2 km/L	₱11.90/km	2026-08-27 13:14:52.392358
VEH-005	NBQ-1108	Tour Bus	Scania	Touring HD 49s	2022	49	Available	\N	Diesel	300	0	0	Healthy	2026-08-16 (Ongoing)	2026-05-12	\N	OR/CR Valid until 2026-11-20	QBE Heavy Fleet - Exp 2026-11-01	CPC No. 2022-77123	0	0	3.5 km/L	₱24.10/km	2026-08-27 13:14:52.392358
VEH-003	NDJ-9920	Coaster Bus	Toyota	Coaster Deluxe	2023	29	Available	\N	Diesel	95	0	0	Healthy	2026-09-28	2026-06-20	\N	OR/CR Valid until 2027-01-18	Pioneer Special Risk - Exp 2026-12-15	CPC No. 2023-45601	0	0	6.4 km/L	₱16.40/km	2026-08-27 13:14:52.392358
VEH-006	CBC-8823	Executive Van	Hyundai	Staria Premium 9s	2023	9	Available	\N	Diesel	75	0	0	Healthy	2026-10-14	2026-07-18	\N	OR/CR Valid until 2027-03-05	Alpha Insurance - Exp 2027-02-28	CPC No. 2023-33901	0	0	11.0 km/L	₱10.90/km	2026-08-27 13:14:52.392358
VEH-007	ZAA-5591	Executive Van	Toyota	HiAce Commuter Deluxe	2023	15	Available	\N	Diesel	70	0	0	Healthy	2026-09-22	2026-06-25	\N	OR/CR Valid until 2027-05-12	FPG Insurance - Exp 2027-04-30	CPC No. 2023-11928	0	0	9.5 km/L	₱12.30/km	2026-08-27 13:14:52.392358
VEH-011	MBK-3302	Executive Van	Toyota	HiAce Grandia	2022	14	Available	\N	Diesel	70	0	0	Healthy	2026-10-21	2026-07-28	\N	OR/CR Valid until 2027-02-08	Standard Charter - Exp 2027-01-20	CPC No. 2023-66431	0	0	9.0 km/L	₱12.60/km	2026-08-27 13:14:52.392358
VEH-012	ZPL-4410	VIP SUV	Nissan	Terra VL 4x4	2023	7	Available	\N	Diesel	80	0	0	Healthy	2026-12-01	2026-08-10	\N	OR/CR Valid until 2027-07-12	Malayan VIP - Exp 2027-06-15	CPC No. 2024-22108	0	0	10.8 km/L	₱10.90/km	2026-08-27 13:14:52.392358
VEH-013	QWE-5512	Tour Bus	King Long	XMQ6127 Coach	2021	48	Available	\N	Diesel	290	0	0	Healthy	2026-09-30	2026-06-30	\N	OR/CR Valid until 2026-12-18	QBE Heavy Fleet - Exp 2026-12-01	CPC No. 2022-33402	0	0	3.7 km/L	₱23.40/km	2026-08-27 13:14:52.392358
VEH-019	JKL-2145	VIP SUV	Toyota	Land Cruiser Prado	2023	7	Available	\N	Diesel	87	0	0	Healthy	2026-12-15	2026-08-12	\N	OR/CR Valid until 2027-08-22	Malayan VIP - Exp 2027-08-01	CPC No. 2024-66102	0	0	9.8 km/L	₱11.70/km	2026-08-27 13:14:52.392358
VEH-020	ZXC-3256	Tour Bus	Scania	Touring HD 45s	2021	45	Available	\N	Diesel	290	0	0	Healthy	2026-09-20	2026-06-28	\N	OR/CR Valid until 2026-11-12	QBE Heavy Fleet - Exp 2026-11-01	CPC No. 2022-11023	0	0	3.6 km/L	₱23.60/km	2026-08-27 13:14:52.392358
VEH-021	BNM-4367	Coaster Bus	Toyota	Coaster Deluxe	2022	29	Available	\N	Diesel	95	0	0	Healthy	2026-10-05	2026-07-12	\N	OR/CR Valid until 2027-01-30	Pioneer Charter - Exp 2026-12-20	CPC No. 2023-88214	0	0	6.3 km/L	₱16.30/km	2026-08-27 13:14:52.392358
VEH-022	VBN-5478	Executive Van	Hyundai	Staria Premium	2023	9	Available	\N	Diesel	75	0	0	Healthy	2026-11-11	2026-08-02	\N	OR/CR Valid until 2027-04-27	Alpha Insurance - Exp 2027-04-10	CPC No. 2023-77105	0	0	10.9 km/L	₱11.00/km	2026-08-27 13:14:52.392358
VEH-023	MNB-6589	Tour Bus	Volvo	B8R Coach	2022	50	Available	\N	Diesel	280	0	0	Healthy	2026-09-25	2026-07-08	\N	OR/CR Valid until 2027-02-11	QBE Heavy Fleet - Exp 2027-01-25	CPC No. 2023-55014	0	0	3.7 km/L	₱23.20/km	2026-08-27 13:14:52.392358
VEH-024	POI-7690	Executive Van	Toyota	HiAce Commuter	2022	15	Available	\N	Diesel	70	0	0	Healthy	2026-10-18	2026-07-20	\N	OR/CR Valid until 2027-03-25	Standard Charter - Exp 2027-03-08	CPC No. 2023-99210	0	0	9.2 km/L	₱12.20/km	2026-08-27 13:14:52.392358
VEH-027	YTR-0932	Tour Bus	Hino	Grand View 49s	2021	49	Available	\N	Diesel	300	0	0	Healthy	2026-08-18 (Ongoing)	2026-05-28	\N	OR/CR Valid until 2026-12-05	QBE Heavy Fleet - Exp 2026-11-28	CPC No. 2022-44019	0	0	3.4 km/L	₱24.50/km	2026-08-27 13:14:52.392358
VEH-028	EWQ-1043	Coaster Bus	Toyota	Coaster Deluxe	2022	29	Available	\N	Diesel	95	0	0	Healthy	2026-08-20 (Scheduled)	2026-07-01	\N	OR/CR Valid until 2027-02-19	Pioneer Charter - Exp 2027-02-01	CPC No. 2023-88102	0	0	6.4 km/L	₱16.20/km	2026-08-27 13:14:52.392358
VEH-015	RTY-7720	Executive Van	Kia	Grand Carnival	2023	14	Available	\N	Diesel	70	0	0	Healthy	2026-11-19	2026-08-14	\N	OR/CR Valid until 2027-05-20	Alpha Insurance - Exp 2027-04-25	CPC No. 2023-91220	0	0	9.4 km/L	₱12.10/km	2026-08-27 13:14:52.392358
VEH-016	UIO-8821	Tour Bus	Hino	RM2P Grand	2022	47	Available	\N	Diesel	260	0	0	Healthy	2026-10-25	2026-07-30	\N	OR/CR Valid until 2027-02-27	QBE Heavy Fleet - Exp 2027-02-10	CPC No. 2023-44105	0	0	3.9 km/L	₱22.90/km	2026-08-27 13:14:52.392358
VEH-017	ASD-9913	Coaster Bus	Toyota	Coaster Deluxe X	2023	29	Available	\N	Diesel	95	0	0	Healthy	2026-11-08	2026-08-08	\N	OR/CR Valid until 2027-06-01	Pioneer Charter - Exp 2027-05-15	CPC No. 2023-33870	0	0	6.7 km/L	₱15.80/km	2026-08-27 13:14:52.392358
VEH-001	NBO-7821	Tour Bus	Hino	Grand View 45s	2023	45	Available	DRV-101	Diesel	250	100	42000	Healthy	2026-12-19	2026-09-20	Inspection Bay	OR/CR Valid until 2027-02-14	Comprehensive QBE - Exp 2027-01-30	CPC No. 2023-88912	1	24	3.8 km/L	₱22.50/km	2026-08-27 13:14:52.392358
\.


--
-- TOC entry 5255 (class 0 OID 0)
-- Dependencies: 218
-- Name: ai_model_registry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ai_model_registry_id_seq', 1, false);


--
-- TOC entry 5256 (class 0 OID 0)
-- Dependencies: 220
-- Name: ai_route_candidates_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ai_route_candidates_log_id_seq', 3, true);


--
-- TOC entry 5257 (class 0 OID 0)
-- Dependencies: 222
-- Name: chart_fuel_monthly_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chart_fuel_monthly_id_seq', 1, false);


--
-- TOC entry 5258 (class 0 OID 0)
-- Dependencies: 224
-- Name: chart_weekly_trips_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chart_weekly_trips_id_seq', 1, false);


--
-- TOC entry 5259 (class 0 OID 0)
-- Dependencies: 226
-- Name: cost_categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cost_categories_id_seq', 1, false);


--
-- TOC entry 5260 (class 0 OID 0)
-- Dependencies: 231
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 3, true);


--
-- TOC entry 5261 (class 0 OID 0)
-- Dependencies: 235
-- Name: permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permissions_id_seq', 17, true);


--
-- TOC entry 5262 (class 0 OID 0)
-- Dependencies: 239
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 4, true);


--
-- TOC entry 5263 (class 0 OID 0)
-- Dependencies: 241
-- Name: route_alternatives_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.route_alternatives_id_seq', 1, false);


--
-- TOC entry 5264 (class 0 OID 0)
-- Dependencies: 243
-- Name: route_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.route_history_id_seq', 1, true);


--
-- TOC entry 5265 (class 0 OID 0)
-- Dependencies: 246
-- Name: route_waypoints_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.route_waypoints_id_seq', 1, false);


--
-- TOC entry 5266 (class 0 OID 0)
-- Dependencies: 248
-- Name: system_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.system_settings_id_seq', 80, true);


--
-- TOC entry 5267 (class 0 OID 0)
-- Dependencies: 250
-- Name: trip_timeline_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trip_timeline_id_seq', 3, true);


--
-- TOC entry 5268 (class 0 OID 0)
-- Dependencies: 253
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- TOC entry 5269 (class 0 OID 0)
-- Dependencies: 255
-- Name: vehicle_cost_categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vehicle_cost_categories_id_seq', 1, false);


--
-- TOC entry 5270 (class 0 OID 0)
-- Dependencies: 257
-- Name: vehicle_cost_ledger_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vehicle_cost_ledger_id_seq', 1, false);


--
-- TOC entry 4945 (class 2606 OID 37010)
-- Name: ai_model_registry ai_model_registry_model_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_model_registry
    ADD CONSTRAINT ai_model_registry_model_id_key UNIQUE (model_id);


--
-- TOC entry 4947 (class 2606 OID 37012)
-- Name: ai_model_registry ai_model_registry_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_model_registry
    ADD CONSTRAINT ai_model_registry_pkey PRIMARY KEY (id);


--
-- TOC entry 4951 (class 2606 OID 37014)
-- Name: ai_route_candidates_log ai_route_candidates_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_route_candidates_log
    ADD CONSTRAINT ai_route_candidates_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4954 (class 2606 OID 37016)
-- Name: chart_fuel_monthly chart_fuel_monthly_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chart_fuel_monthly
    ADD CONSTRAINT chart_fuel_monthly_pkey PRIMARY KEY (id);


--
-- TOC entry 4956 (class 2606 OID 37018)
-- Name: chart_weekly_trips chart_weekly_trips_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chart_weekly_trips
    ADD CONSTRAINT chart_weekly_trips_pkey PRIMARY KEY (id);


--
-- TOC entry 4958 (class 2606 OID 37020)
-- Name: cost_categories cost_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cost_categories
    ADD CONSTRAINT cost_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4960 (class 2606 OID 37022)
-- Name: drivers drivers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);


--
-- TOC entry 4962 (class 2606 OID 37024)
-- Name: fuel_transactions fuel_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fuel_transactions
    ADD CONSTRAINT fuel_transactions_pkey PRIMARY KEY (id);


--
-- TOC entry 4967 (class 2606 OID 37026)
-- Name: maintenance_orders maintenance_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_orders
    ADD CONSTRAINT maintenance_orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4971 (class 2606 OID 37028)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- TOC entry 4977 (class 2606 OID 37030)
-- Name: password_recovery_limits password_recovery_limits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_recovery_limits
    ADD CONSTRAINT password_recovery_limits_pkey PRIMARY KEY (bucket);


--
-- TOC entry 4974 (class 2606 OID 37032)
-- Name: password_recovery password_recovery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_recovery
    ADD CONSTRAINT password_recovery_pkey PRIMARY KEY (id);


--
-- TOC entry 4979 (class 2606 OID 37034)
-- Name: permissions permissions_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_code_key UNIQUE (code);


--
-- TOC entry 4981 (class 2606 OID 37036)
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4985 (class 2606 OID 37038)
-- Name: reservations reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);


--
-- TOC entry 4987 (class 2606 OID 37040)
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id);


--
-- TOC entry 4989 (class 2606 OID 37042)
-- Name: roles roles_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_code_key UNIQUE (code);


--
-- TOC entry 4991 (class 2606 OID 37044)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 4993 (class 2606 OID 37046)
-- Name: route_alternatives route_alternatives_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_alternatives
    ADD CONSTRAINT route_alternatives_pkey PRIMARY KEY (id);


--
-- TOC entry 5000 (class 2606 OID 37048)
-- Name: route_history route_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_history
    ADD CONSTRAINT route_history_pkey PRIMARY KEY (id);


--
-- TOC entry 5004 (class 2606 OID 37050)
-- Name: route_presets route_presets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_presets
    ADD CONSTRAINT route_presets_pkey PRIMARY KEY (id);


--
-- TOC entry 5006 (class 2606 OID 37052)
-- Name: route_waypoints route_waypoints_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_waypoints
    ADD CONSTRAINT route_waypoints_pkey PRIMARY KEY (id);


--
-- TOC entry 5008 (class 2606 OID 37054)
-- Name: system_settings system_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_pkey PRIMARY KEY (id);


--
-- TOC entry 5010 (class 2606 OID 37056)
-- Name: system_settings system_settings_setting_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_setting_key_key UNIQUE (setting_key);


--
-- TOC entry 5012 (class 2606 OID 37058)
-- Name: trip_timeline trip_timeline_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trip_timeline
    ADD CONSTRAINT trip_timeline_pkey PRIMARY KEY (id);


--
-- TOC entry 5016 (class 2606 OID 37060)
-- Name: trips trips_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);


--
-- TOC entry 4995 (class 2606 OID 37062)
-- Name: route_alternatives uq_alt_preset_mode; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_alternatives
    ADD CONSTRAINT uq_alt_preset_mode UNIQUE (preset_id, mode_key);


--
-- TOC entry 5018 (class 2606 OID 37064)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 5020 (class 2606 OID 37066)
-- Name: users users_emp_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_emp_id_key UNIQUE (emp_id);


--
-- TOC entry 5022 (class 2606 OID 37068)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 5025 (class 2606 OID 37070)
-- Name: vehicle_cost_categories vehicle_cost_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicle_cost_categories
    ADD CONSTRAINT vehicle_cost_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 5027 (class 2606 OID 37072)
-- Name: vehicle_cost_ledger vehicle_cost_ledger_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicle_cost_ledger
    ADD CONSTRAINT vehicle_cost_ledger_pkey PRIMARY KEY (id);


--
-- TOC entry 5031 (class 2606 OID 37074)
-- Name: vehicles vehicles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);


--
-- TOC entry 5033 (class 2606 OID 37076)
-- Name: vehicles vehicles_plate_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_plate_number_key UNIQUE (plate_number);


--
-- TOC entry 4952 (class 1259 OID 37077)
-- Name: idx_cand_log; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cand_log ON public.ai_route_candidates_log USING btree (log_id);


--
-- TOC entry 4963 (class 1259 OID 37078)
-- Name: idx_fuel_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_fuel_date ON public.fuel_transactions USING btree (transaction_date);


--
-- TOC entry 4964 (class 1259 OID 37079)
-- Name: idx_fuel_trip; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_fuel_trip ON public.fuel_transactions USING btree (trip_id);


--
-- TOC entry 4948 (class 1259 OID 37080)
-- Name: idx_mdl_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_mdl_status ON public.ai_model_registry USING btree (status);


--
-- TOC entry 4949 (class 1259 OID 37081)
-- Name: idx_mdl_version; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_mdl_version ON public.ai_model_registry USING btree (version);


--
-- TOC entry 4968 (class 1259 OID 37082)
-- Name: idx_notif_read; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notif_read ON public.notifications USING btree (is_read);


--
-- TOC entry 4969 (class 1259 OID 37083)
-- Name: idx_notifications_user_read; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notifications_user_read ON public.notifications USING btree (user_id, is_read);


--
-- TOC entry 4982 (class 1259 OID 37084)
-- Name: idx_res_departure; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_res_departure ON public.reservations USING btree (departure_date);


--
-- TOC entry 4983 (class 1259 OID 37085)
-- Name: idx_res_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_res_status ON public.reservations USING btree (status);


--
-- TOC entry 4996 (class 1259 OID 37086)
-- Name: idx_rh_log; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_rh_log ON public.route_history USING btree (log_id);


--
-- TOC entry 4997 (class 1259 OID 37087)
-- Name: idx_route_history_reservation; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_route_history_reservation ON public.route_history USING btree (reservation_id);


--
-- TOC entry 4998 (class 1259 OID 37088)
-- Name: idx_route_history_trip; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_route_history_trip ON public.route_history USING btree (trip_id);


--
-- TOC entry 5013 (class 1259 OID 37089)
-- Name: idx_trips_route_history; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_trips_route_history ON public.trips USING btree (route_history_id);


--
-- TOC entry 5014 (class 1259 OID 37090)
-- Name: idx_trips_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_trips_status ON public.trips USING btree (status);


--
-- TOC entry 5028 (class 1259 OID 37091)
-- Name: idx_vehicles_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_vehicles_status ON public.vehicles USING btree (status);


--
-- TOC entry 5029 (class 1259 OID 37092)
-- Name: idx_vehicles_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_vehicles_type ON public.vehicles USING btree (type);


--
-- TOC entry 4965 (class 1259 OID 37093)
-- Name: idx_wo_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_wo_status ON public.maintenance_orders USING btree (status);


--
-- TOC entry 4972 (class 1259 OID 37094)
-- Name: password_recovery_expiry_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX password_recovery_expiry_idx ON public.password_recovery USING btree (expires_at);


--
-- TOC entry 4975 (class 1259 OID 37095)
-- Name: password_recovery_user_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX password_recovery_user_idx ON public.password_recovery USING btree (user_id);


--
-- TOC entry 5001 (class 1259 OID 37096)
-- Name: uq_route_history_log_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_route_history_log_id ON public.route_history USING btree (log_id);


--
-- TOC entry 5002 (class 1259 OID 37097)
-- Name: uq_route_history_trip_navigation; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_route_history_trip_navigation ON public.route_history USING btree (trip_id, navigation_key) WHERE ((trip_id IS NOT NULL) AND (navigation_key IS NOT NULL));


--
-- TOC entry 5023 (class 1259 OID 37098)
-- Name: users_recovery_email_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_recovery_email_idx ON public.users USING btree (lower((recovery_email)::text));


--
-- TOC entry 5050 (class 2606 OID 37099)
-- Name: route_alternatives fk_alt_preset; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_alternatives
    ADD CONSTRAINT fk_alt_preset FOREIGN KEY (preset_id) REFERENCES public.route_presets(id) ON DELETE CASCADE;


--
-- TOC entry 5034 (class 2606 OID 37104)
-- Name: ai_route_candidates_log fk_candidate_route_history; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_route_candidates_log
    ADD CONSTRAINT fk_candidate_route_history FOREIGN KEY (log_id) REFERENCES public.route_history(log_id) ON DELETE CASCADE;


--
-- TOC entry 5035 (class 2606 OID 37109)
-- Name: drivers fk_drivers_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT fk_drivers_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5036 (class 2606 OID 37114)
-- Name: fuel_transactions fk_fuel_driver; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fuel_transactions
    ADD CONSTRAINT fk_fuel_driver FOREIGN KEY (driver_id) REFERENCES public.drivers(id) ON DELETE SET NULL;


--
-- TOC entry 5037 (class 2606 OID 37119)
-- Name: fuel_transactions fk_fuel_trip; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fuel_transactions
    ADD CONSTRAINT fk_fuel_trip FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON DELETE SET NULL;


--
-- TOC entry 5038 (class 2606 OID 37124)
-- Name: fuel_transactions fk_fuel_vehicle; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fuel_transactions
    ADD CONSTRAINT fk_fuel_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE CASCADE;


--
-- TOC entry 5061 (class 2606 OID 37129)
-- Name: vehicle_cost_ledger fk_ledger_vehicle; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicle_cost_ledger
    ADD CONSTRAINT fk_ledger_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE CASCADE;


--
-- TOC entry 5039 (class 2606 OID 37134)
-- Name: maintenance_orders fk_maintenance_source_trip; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_orders
    ADD CONSTRAINT fk_maintenance_source_trip FOREIGN KEY (source_trip_id) REFERENCES public.trips(id) ON DELETE SET NULL;


--
-- TOC entry 5041 (class 2606 OID 37139)
-- Name: notifications fk_notifications_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5043 (class 2606 OID 37144)
-- Name: reservations fk_res_cancelled_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk_res_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5044 (class 2606 OID 37149)
-- Name: reservations fk_res_cancelled_driver; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk_res_cancelled_driver FOREIGN KEY (cancelled_driver_id) REFERENCES public.drivers(id) ON DELETE SET NULL;


--
-- TOC entry 5045 (class 2606 OID 37154)
-- Name: reservations fk_res_cancelled_vehicle; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk_res_cancelled_vehicle FOREIGN KEY (cancelled_vehicle_id) REFERENCES public.vehicles(id) ON DELETE SET NULL;


--
-- TOC entry 5046 (class 2606 OID 37159)
-- Name: reservations fk_res_driver; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk_res_driver FOREIGN KEY (assigned_driver_id) REFERENCES public.drivers(id) ON DELETE SET NULL;


--
-- TOC entry 5047 (class 2606 OID 37164)
-- Name: reservations fk_res_vehicle; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk_res_vehicle FOREIGN KEY (assigned_vehicle_id) REFERENCES public.vehicles(id) ON DELETE SET NULL;


--
-- TOC entry 5051 (class 2606 OID 37169)
-- Name: route_history fk_rh_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_history
    ADD CONSTRAINT fk_rh_user FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5052 (class 2606 OID 37174)
-- Name: route_history fk_route_history_reservation; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_history
    ADD CONSTRAINT fk_route_history_reservation FOREIGN KEY (reservation_id) REFERENCES public.reservations(id) ON DELETE SET NULL;


--
-- TOC entry 5053 (class 2606 OID 37179)
-- Name: route_history fk_route_history_trip; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_history
    ADD CONSTRAINT fk_route_history_trip FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON DELETE SET NULL;


--
-- TOC entry 5048 (class 2606 OID 37184)
-- Name: role_permissions fk_rp_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES public.permissions(id) ON DELETE CASCADE;


--
-- TOC entry 5049 (class 2606 OID 37189)
-- Name: role_permissions fk_rp_role; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- TOC entry 5055 (class 2606 OID 37194)
-- Name: trip_timeline fk_tl_trip; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trip_timeline
    ADD CONSTRAINT fk_tl_trip FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON DELETE CASCADE;


--
-- TOC entry 5056 (class 2606 OID 37199)
-- Name: trips fk_trips_driver; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fk_trips_driver FOREIGN KEY (driver_id) REFERENCES public.drivers(id) ON DELETE SET NULL;


--
-- TOC entry 5057 (class 2606 OID 37204)
-- Name: trips fk_trips_reservation; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fk_trips_reservation FOREIGN KEY (reservation_id) REFERENCES public.reservations(id) ON DELETE SET NULL;


--
-- TOC entry 5058 (class 2606 OID 37209)
-- Name: trips fk_trips_route_history; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fk_trips_route_history FOREIGN KEY (route_history_id) REFERENCES public.route_history(log_id) ON DELETE SET NULL;


--
-- TOC entry 5059 (class 2606 OID 37214)
-- Name: trips fk_trips_vehicle; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fk_trips_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE SET NULL;


--
-- TOC entry 5060 (class 2606 OID 37219)
-- Name: users fk_users_role; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- TOC entry 5062 (class 2606 OID 37224)
-- Name: vehicles fk_vehicles_driver; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT fk_vehicles_driver FOREIGN KEY (assigned_driver_id) REFERENCES public.drivers(id) ON DELETE SET NULL;


--
-- TOC entry 5040 (class 2606 OID 37229)
-- Name: maintenance_orders fk_wo_vehicle; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_orders
    ADD CONSTRAINT fk_wo_vehicle FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE CASCADE;


--
-- TOC entry 5054 (class 2606 OID 37234)
-- Name: route_waypoints fk_wp_preset; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_waypoints
    ADD CONSTRAINT fk_wp_preset FOREIGN KEY (preset_id) REFERENCES public.route_presets(id) ON DELETE CASCADE;


--
-- TOC entry 5042 (class 2606 OID 37239)
-- Name: password_recovery password_recovery_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_recovery
    ADD CONSTRAINT password_recovery_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


-- Completed on 2026-09-23 09:26:04

--
-- PostgreSQL database dump complete
--

\unrestrict mIlo6xJ2QAFDbsOWQj6NmsJDoo1o2ibxiH7Zes4fH4KN92DUJ0lZNnCdvlSPxjf

