 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

DROP TABLE IF EXISTS role_permissions, trip_timeline, maintenance_orders, fuel_transactions, vehicle_cost_ledger, route_waypoints, route_alternatives, route_history, ai_route_candidates_log, ai_model_registry, notifications, system_settings, trips, reservations, vehicles, drivers, users, permissions, roles, vehicle_cost_categories, cost_categories, chart_weekly_trips, chart_fuel_monthly, route_presets CASCADE;

 
 
 

CREATE TABLE roles (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          VARCHAR(50)  NOT NULL UNIQUE,
  name          VARCHAR(100) NOT NULL,
  description   VARCHAR(255) DEFAULT NULL
);

CREATE TABLE permissions (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          VARCHAR(100) NOT NULL UNIQUE,
  name          VARCHAR(150) NOT NULL,
  module        VARCHAR(100) DEFAULT NULL
);

CREATE TABLE role_permissions (
  role_id       INT NOT NULL,
  permission_id INT NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id        VARCHAR(30)  NOT NULL UNIQUE,
  name          VARCHAR(120) NOT NULL,
  email         VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role_id       INT NOT NULL,
  department    VARCHAR(150) DEFAULT NULL,
  avatar        VARCHAR(500) DEFAULT NULL,
  status        VARCHAR(20) CHECK (status IN ('Active','Inactive')) NOT NULL DEFAULT 'Active',
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

 
 
 

CREATE TABLE drivers (
  id                  VARCHAR(20) NOT NULL PRIMARY KEY,    
  user_id             INT DEFAULT NULL,                    
  name                VARCHAR(120) NOT NULL,
  emp_id              VARCHAR(30) DEFAULT NULL,
  phone               VARCHAR(40) DEFAULT NULL,
  license_no          VARCHAR(40) DEFAULT NULL,
  license_class       VARCHAR(100) DEFAULT NULL,
  license_expiration  DATE DEFAULT NULL,
  status              VARCHAR(30) NOT NULL DEFAULT 'Active',
  safety_score        INT NOT NULL DEFAULT 95,
  on_time_rate        DECIMAL(5,2) NOT NULL DEFAULT 97.00,
  fuel_efficiency_score INT NOT NULL DEFAULT 90,
  rating              DECIMAL(3,2) NOT NULL DEFAULT 4.80,
  trip_count          INT NOT NULL DEFAULT 0,
  completed_trips     INT NOT NULL DEFAULT 0,
  cancelled_trips     INT NOT NULL DEFAULT 0,
  department          VARCHAR(150) DEFAULT NULL,
  hrms_status         VARCHAR(200) DEFAULT NULL,
  CONSTRAINT fk_drivers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE vehicles (
  id                  VARCHAR(20) NOT NULL PRIMARY KEY,    
  plate_number        VARCHAR(20) NOT NULL UNIQUE,
  type                VARCHAR(60) NOT NULL,
  brand               VARCHAR(60) NOT NULL,
  model               VARCHAR(100) NOT NULL,
  year                INT NOT NULL,
  capacity            INT NOT NULL,
  status              VARCHAR(30) NOT NULL DEFAULT 'Available',
  assigned_driver_id  VARCHAR(20) DEFAULT NULL,
  fuel_type           VARCHAR(30) DEFAULT NULL,
  fuel_capacity       INT DEFAULT NULL,
  current_fuel        INT DEFAULT NULL,
  odometer            INT DEFAULT NULL,
  maintenance_status  VARCHAR(150) DEFAULT NULL,
  next_maintenance    VARCHAR(50) DEFAULT NULL,
  last_maintenance    VARCHAR(50) DEFAULT NULL,
  location            VARCHAR(200) DEFAULT NULL,
  reg_document        VARCHAR(200) DEFAULT NULL,
  insurance_document  VARCHAR(200) DEFAULT NULL,
  ltfrb_permit        VARCHAR(200) DEFAULT NULL,
  total_trips         INT NOT NULL DEFAULT 0,
  total_km            INT NOT NULL DEFAULT 0,
  avg_fuel_km         VARCHAR(20) DEFAULT NULL,
  operating_cost_km   VARCHAR(20) DEFAULT NULL,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vehicles_driver FOREIGN KEY (assigned_driver_id) REFERENCES drivers(id) ON DELETE SET NULL
);

CREATE TABLE reservations (
  id                  VARCHAR(30) NOT NULL PRIMARY KEY,    
  client_name         VARCHAR(150) NOT NULL,
  contact_person      VARCHAR(120) DEFAULT NULL,
  contact_phone       VARCHAR(40) DEFAULT NULL,
  passenger_count     INT NOT NULL,
  origin              VARCHAR(200) NOT NULL,
  destination         VARCHAR(200) NOT NULL,
  departure_date      DATE NOT NULL,
  departure_time      VARCHAR(20) DEFAULT NULL,
  return_date         DATE DEFAULT NULL,
  vehicle_requested   VARCHAR(120) DEFAULT NULL,
  assigned_vehicle_id VARCHAR(20) DEFAULT NULL,
  assigned_driver_id  VARCHAR(20) DEFAULT NULL,
  status              VARCHAR(30) NOT NULL DEFAULT 'Pending',
  trip_type           VARCHAR(120) DEFAULT NULL,
  notes               TEXT DEFAULT NULL,
  estimated_cost      DECIMAL(12,2) DEFAULT NULL,
  cancellation_type   VARCHAR(30) DEFAULT NULL,
  cancellation_reason VARCHAR(120) DEFAULT NULL,
  cancellation_notes  TEXT DEFAULT NULL,
  cancelled_by        INTEGER DEFAULT NULL,
  cancelled_at        TIMESTAMP DEFAULT NULL,
  cancelled_vehicle_id VARCHAR(20) DEFAULT NULL,
  cancelled_driver_id VARCHAR(20) DEFAULT NULL,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_res_vehicle FOREIGN KEY (assigned_vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL,
  CONSTRAINT fk_res_driver FOREIGN KEY (assigned_driver_id) REFERENCES drivers(id) ON DELETE SET NULL,
  CONSTRAINT fk_res_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_res_cancelled_vehicle FOREIGN KEY (cancelled_vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL,
  CONSTRAINT fk_res_cancelled_driver FOREIGN KEY (cancelled_driver_id) REFERENCES drivers(id) ON DELETE SET NULL
);

CREATE TABLE trips (
  id                  VARCHAR(20) NOT NULL PRIMARY KEY,    
  reservation_id      VARCHAR(30) DEFAULT NULL,
  origin              VARCHAR(200) NOT NULL,
  destination         VARCHAR(200) NOT NULL,
  waypoints           VARCHAR(300) DEFAULT NULL,
  vehicle_id          VARCHAR(20) DEFAULT NULL,
  driver_id           VARCHAR(20) DEFAULT NULL,
  passengers          INT DEFAULT NULL,
  scheduled_departure TIMESTAMP DEFAULT NULL,
  actual_departure    TIMESTAMP DEFAULT NULL,
  estimated_arrival   TIMESTAMP DEFAULT NULL,
  actual_arrival      TIMESTAMP DEFAULT NULL,
  distance_km         DECIMAL(6,1) DEFAULT NULL,
  status              VARCHAR(30) NOT NULL DEFAULT 'Scheduled',
  progress_pct        INT NOT NULL DEFAULT 0,
  current_step        VARCHAR(120) DEFAULT NULL,
  fuel_estimate       VARCHAR(60) DEFAULT NULL,
  toll_fee            DECIMAL(10,2) DEFAULT NULL,
  driver_allowance    DECIMAL(10,2) DEFAULT NULL,
  total_cost          DECIMAL(12,2) DEFAULT NULL,
  route_history_id    VARCHAR(30) DEFAULT NULL,
  navigation_active   SMALLINT NOT NULL DEFAULT 0 CHECK (navigation_active IN (0,1)),
  final_odometer      INT DEFAULT NULL,
  vehicle_condition   VARCHAR(40) DEFAULT NULL,
  completion_notes    TEXT DEFAULT NULL,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_trips_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE SET NULL,
  CONSTRAINT fk_trips_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL,
  CONSTRAINT fk_trips_driver FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL
);

CREATE TABLE trip_timeline (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id      VARCHAR(20) NOT NULL,
  title        VARCHAR(200) NOT NULL,
  event_time   VARCHAR(60) DEFAULT NULL,
  completed    SMALLINT NOT NULL DEFAULT 0,
  active_step  SMALLINT NOT NULL DEFAULT 0,
  sort_order   INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_tl_trip FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE
);

CREATE TABLE maintenance_orders (
  id             VARCHAR(30) NOT NULL PRIMARY KEY,         
  vehicle_id     VARCHAR(20) NOT NULL,
  service_type   VARCHAR(200) NOT NULL,
  priority       VARCHAR(20) CHECK (priority IN ('Critical','Medium','Low')) NOT NULL DEFAULT 'Medium',
  scheduled_date DATE NOT NULL,
  status         VARCHAR(30) NOT NULL DEFAULT 'Scheduled',
  estimated_cost DECIMAL(12,2) DEFAULT NULL,
  notes          TEXT DEFAULT NULL,
  source_trip_id VARCHAR(20) DEFAULT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_wo_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,
  CONSTRAINT fk_wo_source_trip FOREIGN KEY (source_trip_id) REFERENCES trips(id) ON DELETE SET NULL
);

CREATE TABLE fuel_transactions (
  id              VARCHAR(30) NOT NULL PRIMARY KEY,        
  vehicle_id      VARCHAR(20) NOT NULL,
  driver_id       VARCHAR(20) DEFAULT NULL,
  trip_id         VARCHAR(20) DEFAULT NULL,
  transaction_date TIMESTAMP NOT NULL,
  fuel_type       VARCHAR(30) DEFAULT 'Diesel',
  liters          DECIMAL(8,2) NOT NULL,
  price_per_liter DECIMAL(8,2) NOT NULL,
  total_cost      DECIMAL(12,2) NOT NULL,
  odometer        INT DEFAULT NULL,
  station         VARCHAR(200) DEFAULT NULL,
  receipt_no      VARCHAR(40) DEFAULT NULL,
  efficiency      VARCHAR(20) DEFAULT NULL,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_fuel_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,
  CONSTRAINT fk_fuel_driver FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL,
  CONSTRAINT fk_fuel_trip FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE SET NULL
);

 
 
 

CREATE TABLE vehicle_cost_categories (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name  VARCHAR(120) NOT NULL,
  active_units   INT NOT NULL,
  monthly_expense DECIMAL(12,2) NOT NULL,
  cost_per_km    VARCHAR(20) DEFAULT NULL,
  sort_order     INT NOT NULL DEFAULT 0
);

CREATE TABLE cost_categories (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(120) NOT NULL,
  amount      DECIMAL(12,2) NOT NULL,
  pct         DECIMAL(5,2) NOT NULL,
  color       VARCHAR(20) NOT NULL,
  sort_order  INT NOT NULL DEFAULT 0
);

 
CREATE TABLE vehicle_cost_ledger (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id       VARCHAR(20) NOT NULL,
  plate_number     VARCHAR(20) NOT NULL,
  model            VARCHAR(100) NOT NULL,
  fuel_cost        DECIMAL(12,2) NOT NULL DEFAULT 0,
  maintenance_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
  driver_expense   DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_cost       DECIMAL(12,2) NOT NULL DEFAULT 0,
  sort_order       INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_ledger_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
);

CREATE TABLE chart_weekly_trips (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_name        VARCHAR(10) NOT NULL,
  trips_completed INT NOT NULL,
  sort_order      INT NOT NULL
);

CREATE TABLE chart_fuel_monthly (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month_label VARCHAR(10) NOT NULL,
  expense     DECIMAL(12,2) NOT NULL,
  sort_order  INT NOT NULL
);

 
 
 

CREATE TABLE route_presets (
  id                 VARCHAR(30) NOT NULL PRIMARY KEY,     
  name               VARCHAR(200) NOT NULL,
  origin             VARCHAR(200) NOT NULL,
  origin_lat         DECIMAL(10,6) NOT NULL,
  origin_lng         DECIMAL(10,6) NOT NULL,
  destination        VARCHAR(200) NOT NULL,
  dest_lat           DECIMAL(10,6) NOT NULL,
  dest_lng           DECIMAL(10,6) NOT NULL,
  passenger_count    INT NOT NULL,
  recommended_vehicle VARCHAR(150) DEFAULT NULL
);

CREATE TABLE route_waypoints (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  preset_id  VARCHAR(30) NOT NULL,
  name       VARCHAR(200) NOT NULL,
  lat        DECIMAL(10,6) NOT NULL,
  lng        DECIMAL(10,6) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_wp_preset FOREIGN KEY (preset_id) REFERENCES route_presets(id) ON DELETE CASCADE
);

CREATE TABLE route_alternatives (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  preset_id        VARCHAR(30) NOT NULL,
  mode_key         VARCHAR(30) NOT NULL,     
  title            VARCHAR(200) NOT NULL,
  distance         VARCHAR(30) NOT NULL,
  duration         VARCHAR(30) NOT NULL,
  fuel_estimate    VARCHAR(60) NOT NULL,
  toll_estimate    VARCHAR(30) DEFAULT NULL,
  total_trip_cost  VARCHAR(40) NOT NULL,
  route_score      VARCHAR(20) NOT NULL,
  reason           TEXT DEFAULT NULL,
  CONSTRAINT fk_alt_preset FOREIGN KEY (preset_id) REFERENCES route_presets(id) ON DELETE CASCADE,
  CONSTRAINT uq_alt_preset_mode UNIQUE (preset_id, mode_key)
);

CREATE TABLE route_history (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_id                 VARCHAR(30) NOT NULL UNIQUE,     
  route_title            VARCHAR(200) NOT NULL,
  vehicle                VARCHAR(120) DEFAULT NULL,
  vehicle_id             VARCHAR(20) DEFAULT NULL,
  generated_date         TIMESTAMP NOT NULL,
  selected_mode          VARCHAR(60) DEFAULT NULL,
  variance_accuracy      VARCHAR(40) DEFAULT NULL,
  model_version          VARCHAR(30) DEFAULT 'v0-kinematic',
  predicted_duration_mins INT DEFAULT NULL,
  predicted_fuel_liters  DECIMAL(7,2) DEFAULT NULL,
  actual_duration_mins   INT DEFAULT NULL,
  actual_fuel_liters     DECIMAL(7,2) DEFAULT NULL,
  variance_pct           DECIMAL(5,2) DEFAULT NULL,
  pre_trip_features_json TEXT DEFAULT NULL,
  reservation_id         VARCHAR(30) DEFAULT NULL,
  trip_id                VARCHAR(20) DEFAULT NULL,
  origin                 VARCHAR(200) DEFAULT NULL,
  destination            VARCHAR(200) DEFAULT NULL,
  waypoints_json         TEXT DEFAULT NULL,
  route_data_json        TEXT DEFAULT NULL,
  navigation_key         VARCHAR(64) DEFAULT NULL,
  created_by             INT DEFAULT NULL,
  CONSTRAINT fk_rh_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_rh_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE SET NULL,
  CONSTRAINT fk_rh_trip FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE SET NULL
);

ALTER TABLE trips
  ADD CONSTRAINT fk_trips_route_history FOREIGN KEY (route_history_id) REFERENCES route_history(log_id) ON DELETE SET NULL;

CREATE TABLE ai_model_registry (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id             VARCHAR(50) NOT NULL UNIQUE,           
  version              VARCHAR(20) NOT NULL,                  
  algorithm            VARCHAR(80) NOT NULL,                  
  target_variable      VARCHAR(50) NOT NULL,                  
  training_samples     INT NOT NULL DEFAULT 0,
  validation_samples   INT NOT NULL DEFAULT 0,
  mae                  DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
  rmse                 DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
  r2_score             DECIMAL(6,4) NOT NULL DEFAULT 0.0000,
  feature_list_json    TEXT NOT NULL,
  hyperparameters_json TEXT DEFAULT NULL,
  weights_json         TEXT NOT NULL,
  status               VARCHAR(20) CHECK (status IN ('ColdStart','Experimental','Validated','Deployed','Deprecated')) NOT NULL DEFAULT 'ColdStart',
  deployed_at          TIMESTAMP DEFAULT NULL,
  created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_route_candidates_log (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_id                VARCHAR(30) NOT NULL,
  candidate_index       INT NOT NULL DEFAULT 0,
  summary_title         VARCHAR(200) NOT NULL,
  distance_km           DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  duration_mins         INT NOT NULL DEFAULT 0,
  traffic_duration_mins INT NOT NULL DEFAULT 0,
  estimated_fuel_l      DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  toll_cost_est         DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  composite_score       INT NOT NULL DEFAULT 0,
  is_selected           SMALLINT NOT NULL DEFAULT 0,
  created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_candidate_route_history FOREIGN KEY (log_id) REFERENCES route_history(log_id) ON DELETE CASCADE
);

 
 
 

CREATE TABLE notifications (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       VARCHAR(200) NOT NULL,
  body        TEXT NOT NULL,
  time_label  VARCHAR(60) DEFAULT NULL,
  type        VARCHAR(20) NOT NULL DEFAULT 'info',
  category    VARCHAR(50) DEFAULT NULL,
  target      VARCHAR(60) DEFAULT NULL,
  is_read     SMALLINT NOT NULL DEFAULT 0,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id     INT DEFAULT NULL,
  CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE system_settings (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key   VARCHAR(80) NOT NULL UNIQUE,
  setting_value VARCHAR(500) DEFAULT NULL,
  description   VARCHAR(255) DEFAULT NULL
);

 
CREATE INDEX idx_vehicles_status ON vehicles(status);
CREATE INDEX idx_vehicles_type ON vehicles(type);
CREATE INDEX idx_res_status ON reservations(status);
CREATE INDEX idx_res_departure ON reservations(departure_date);
CREATE INDEX idx_trips_status ON trips(status);
CREATE INDEX idx_trips_route_history ON trips(route_history_id);
CREATE INDEX idx_wo_status ON maintenance_orders(status);
CREATE INDEX idx_fuel_date ON fuel_transactions(transaction_date);
CREATE INDEX idx_fuel_trip ON fuel_transactions(trip_id);
CREATE INDEX idx_rh_log ON route_history(log_id);
CREATE INDEX idx_rh_trip ON route_history(trip_id);
CREATE UNIQUE INDEX uq_rh_trip_navigation ON route_history(trip_id,navigation_key) WHERE trip_id IS NOT NULL AND navigation_key IS NOT NULL;
CREATE INDEX idx_mdl_status ON ai_model_registry(status);
CREATE INDEX idx_mdl_version ON ai_model_registry(version);
CREATE INDEX idx_cand_log ON ai_route_candidates_log(log_id);
CREATE INDEX idx_notif_read ON notifications(is_read);

 
 
 

 
 
 
INSERT INTO roles (code, name, description) VALUES
('fleet_admin',  'Fleet Administrator', 'Full console access to every module and system settings.'),
('fleet_manager','Fleet Manager',       'Vehicle, cost and AI route management; dispatch view-only.'),
('dispatcher',   'Dispatcher',          'Reservation and dispatch workflow; cost view-only.'),
('driver',       'Driver',              'Driver portal: own trips, assigned vehicle and route info.');

 
 
 
INSERT INTO permissions (code, name, module) VALUES
('vehicles.view',    'View Vehicle Directory',         'Fleet & Vehicle Management'),
('vehicles.assign',  'Assign Vehicles & Drivers',      'Fleet & Vehicle Management'),
('vehicles.manage',  'Manage Vehicle Records (CRUD)',  'Fleet & Vehicle Management'),
('dispatch.view',    'View Reservations & Dispatch',   'Reservation & Dispatch'),
('dispatch.manage',  'Manage Dispatch Workflow',       'Reservation & Dispatch'),
('drivers.view',     'View Driver Performance',        'Driver & Trip Performance'),
('fuel.view',        'View Fuel Management',           'Fuel Management'),
('fuel.manage',      'Manage Fuel Transactions',       'Fuel Management'),
('costs.view',       'View Cost Analysis',             'Cost Analysis (TCAO)'),
('costs.manage',     'Manage Cost Configuration',      'Cost Analysis (TCAO)'),
('ai.view',          'View AI Route Optimization',     'AI Route Optimization'),
('ai.manage',        'Manage AI Route Generation',     'AI Route Optimization'),
('ai.navigate',      'Navigate Assigned Route',        'AI Route Optimization'),
('reports.view',     'View & Generate Reports',        'System'),
('settings.manage',  'Manage System Settings & RBAC',  'System'),
('notifications.view','View Notifications Center',     'System'),
('driver.portal',    'Access Driver Portal',           'Driver Portal');

 
 
 
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'fleet_admin';

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'fleet_manager'
  AND p.code IN ('vehicles.view','vehicles.assign','vehicles.manage','dispatch.view',
                 'drivers.view','fuel.view','fuel.manage','costs.view','costs.manage',
                 'ai.view','ai.manage','ai.navigate','reports.view','notifications.view');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'dispatcher'
  AND p.code IN ('vehicles.view','vehicles.assign','dispatch.view','dispatch.manage',
                 'drivers.view','fuel.view','costs.view','ai.view','ai.manage','ai.navigate',
                 'reports.view','notifications.view');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'driver'
  AND p.code IN ('driver.portal','fuel.view','fuel.manage','ai.view','ai.navigate','notifications.view');

 
 
 
 
 
INSERT INTO users (emp_id, name, email, password_hash, role_id, department, avatar) VALUES
('EMP-TC-8802', 'Alex Ramirez', 'a.ramirez@toursphere.com',
 '$2y$10$966WZewSGNy1wR3zQxSHeeknXWlggbvblFmWP2WOzlACodEactjsi',
 (SELECT id FROM roles WHERE code='fleet_admin'),
 'Fleet Operations & Logistics',
 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80'),
('EMP-TC-7601', 'Patricia Lim', 'manager.fleet@toursphere.com',
 '$2y$10$966WZewSGNy1wR3zQxSHeeknXWlggbvblFmWP2WOzlACodEactjsi',
 (SELECT id FROM roles WHERE code='fleet_manager'),
 'Fleet Operations & Logistics',
 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80'),
('EMP-TC-5320', 'Kevin Torres', 'dispatch.ops@toursphere.com',
 '$2y$10$966WZewSGNy1wR3zQxSHeeknXWlggbvblFmWP2WOzlACodEactjsi',
 (SELECT id FROM roles WHERE code='dispatcher'),
 'Dispatch & Reservations',
 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80'),
('EMP-TC-0412', 'Danilo Santos', 'd.santos@toursphere.com',
 '$2y$10$966WZewSGNy1wR3zQxSHeeknXWlggbvblFmWP2WOzlACodEactjsi',
 (SELECT id FROM roles WHERE code='driver'),
 'Heavy Transport Unit',
 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=120&auto=format&fit=crop&q=80');

 
 
 
INSERT INTO drivers (id, user_id, name, emp_id, phone, license_no, license_class,
                     license_expiration, status, safety_score, on_time_rate,
                     fuel_efficiency_score, rating, trip_count, completed_trips,
                     cancelled_trips, department, hrms_status) VALUES
('DRV-101', 4,  'Danilo Santos',     'EMP-TC-0412', '+63 917 555 0192', 'N01-12-887412', 'Professional (Class 2, 3)', '2028-11-20', 'Active', 99, 98.50, 94, 4.90, 214, 211, 3,  'Heavy Transport Unit',   'Synced with HRMS (Full-Time Regular)'),
('DRV-102', NULL, 'Reynaldo Ramos',  'EMP-TC-0488', '+63 920 443 1890', 'N02-14-663910', 'Professional (Class 1, 2)', '2027-08-14', 'On Trip', 96, 97.20, 92, 4.80, 260, 257, 3,  'Executive Tour Unit',    'Synced with HRMS (Full-Time Regular)'),
('DRV-103', NULL, 'Eduardo Cruz',    'EMP-TC-0511', '+63 918 331 7721', 'N01-15-990234', 'Professional (Class 2, 3)', '2028-03-09', 'On Trip', 98, 95.80, 90, 4.70, 180, 178, 2,  'Charter Group Unit',     'Synced with HRMS (Full-Time Regular)'),
('DRV-104', NULL, 'Mark Bautista',   'EMP-TC-0624', '+63 917 882 3410', 'N03-18-112903', 'Professional (Class 1, 2)', '2029-01-25', 'Active', 100, 99.10, 96, 5.00, 112, 110, 2,  'VIP Concierge Fleet',    'Synced with HRMS (Full-Time Regular)'),
('DRV-105', NULL, 'Roberto Chavez',  'EMP-TC-0570', '+63 915 770 2214', 'N01-13-338910', 'Professional (Class 1, 2)', '2028-06-30', 'Active', 93, 95.00, 88, 4.60, 148, 145, 3,  'Executive Tour Unit',    'Synced with HRMS (Full-Time Regular)'),
('DRV-106', NULL, 'Arnel Mendoza',   'EMP-TC-0550', '+63 929 110 8823', 'N02-16-440192', 'Professional (Class 1, 2)', '2027-12-05', 'Active', 95, 96.40, 91, 4.80, 162, 159, 3,  'Executive Tour Unit',    'Synced with HRMS (Full-Time Regular)'),
('DRV-107', NULL, 'Ferdinand Lopez', 'EMP-TC-0499', '+63 916 228 9011', 'N01-13-771890', 'Professional (Class 1, 2)', '2028-05-18', 'Active', 94, 94.90, 89, 4.60, 220, 216, 4,  'Charter Group Unit',     'Synced with HRMS (Full-Time Regular)'),
('DRV-108', NULL, 'Joseph Tan',      'EMP-TC-0380', '+63 917 662 4589', 'N01-11-229871', 'Professional (Class 2, 3)', '2028-09-12', 'On Trip', 97, 98.00, 93, 4.90, 235, 230, 5,  'Heavy Transport Unit',   'Synced with HRMS (Full-Time Regular)'),
('DRV-109', NULL, 'Miguel Santos',   'EMP-TC-0640', '+63 918 440 7718', 'N02-12-556701', 'Professional (Class 1, 2)', '2027-10-22', 'Active', 92, 95.50, 87, 4.50, 130, 127, 3,  'Charter Group Unit',     'Synced with HRMS (Full-Time Regular)'),
('DRV-110', NULL, 'Liza Marquez',    'EMP-TC-0671', '+63 917 889 1023', 'N03-09-664512', 'Professional (Class 1)',    '2028-02-14', 'Active', 96, 97.80, 92, 4.80, 121, 119, 2,  'VIP Concierge Fleet',    'Synced with HRMS (Full-Time Regular)'),
('DRV-111', NULL, 'Ramon Dela Cruz', 'EMP-TC-0702', '+63 920 311 8840', 'N01-17-120394', 'Professional (Class 2, 3)', '2029-04-01', 'Active', 91, 94.20, 86, 4.40, 175, 171, 4,  'Heavy Transport Unit',   'Synced with HRMS (Full-Time Regular)'),
('DRV-112', NULL, 'Dennis Aquino',   'EMP-TC-0445', '+63 919 556 3381', 'N02-11-908871', 'Professional (Class 1, 2)', '2027-11-30', 'On Trip', 95, 96.90, 90, 4.70, 158, 155, 3,  'Executive Tour Unit',    'Synced with HRMS (Full-Time Regular)'),
('DRV-113', NULL, 'Joel Garcia',     'EMP-TC-0612', '+63 915 662 0041', 'N01-14-778205', 'Professional (Class 2, 3)', '2028-08-19', 'On Trip', 94, 95.70, 89, 4.60, 142, 139, 3,  'Charter Group Unit',     'Synced with HRMS (Full-Time Regular)'),
('DRV-114', NULL, 'Crispin Reyes',   'EMP-TC-0690', '+63 917 334 5566', 'N02-15-331002', 'Professional (Class 1, 2)', '2027-09-08', 'On Trip', 90, 94.00, 85, 4.30, 118, 115, 3,  'Executive Tour Unit',    'Synced with HRMS (Full-Time Regular)'),
('DRV-115', NULL, 'Noel Villanueva', 'EMP-TC-0523', '+63 918 772 9145', 'N01-12-556678', 'Professional (Class 2, 3)', '2028-12-25', 'On Trip', 97, 97.50, 93, 4.90, 196, 192, 4,  'Heavy Transport Unit',   'Synced with HRMS (Full-Time Regular)'),
('DRV-116', NULL, 'Alvin Bautista',  'EMP-TC-0658', '+63 920 118 4477', 'N03-13-229076', 'Professional (Class 1, 2)', '2029-02-28', 'On Trip', 93, 95.10, 88, 4.60, 133, 130, 3,  'Charter Group Unit',     'Synced with HRMS (Full-Time Regular)'),
('DRV-117', NULL, 'Mario Torres',    'EMP-TC-0715', '+63 917 990 2230', 'N02-18-904412', 'Professional (Class 2, 3)', '2028-07-16', 'On Trip', 92, 94.80, 87, 4.50, 151, 147, 4,  'Heavy Transport Unit',   'Synced with HRMS (Full-Time Regular)'),
('DRV-118', NULL, 'Victor Santos',   'EMP-TC-0584', '+63 915 445 6677', 'N01-10-667781', 'Professional (Class 1, 2)', '2027-12-09', 'Assigned', 96, 97.00, 91, 4.80, 169, 166, 3,  'Executive Tour Unit',    'Synced with HRMS (Full-Time Regular)');

 
 
 
INSERT INTO vehicles (id, plate_number, type, brand, model, year, capacity, status,
  assigned_driver_id, fuel_type, fuel_capacity, current_fuel, odometer, maintenance_status,
  next_maintenance, last_maintenance, location, reg_document, insurance_document, ltfrb_permit,
  total_trips, total_km, avg_fuel_km, operating_cost_km) VALUES
('VEH-001', 'NBO-7821', 'Tour Bus',       'Hino',     'Grand View 45s', 2023, 45, 'Available', 'DRV-101', 'Diesel', 250, 88, 42350, 'Healthy', '2026-09-15', '2026-06-10', 'Central Depot - Bay 4',     'OR/CR Valid until 2027-02-14', 'Comprehensive QBE - Exp 2027-01-30', 'CPC No. 2023-88912', 184, 42350, '3.8 km/L', '₱22.50/km'),
('VEH-002', 'CAV-4519', 'Executive Van',  'Toyota',   'HiAce Grandia Tourer', 2024, 14, 'On Trip', 'DRV-102', 'Diesel', 70, 65, 28400, 'Healthy', '2026-10-02', '2026-07-05', 'In Transit: Manila → Tagaytay', 'OR/CR Valid until 2027-04-10', 'Standard Charter - Exp 2027-03-22', 'CPC No. 2024-11045', 242, 28400, '9.2 km/L', '₱12.80/km'),
('VEH-003', 'NDJ-9920', 'Coaster Bus',    'Toyota',   'Coaster Deluxe', 2023, 29, 'On Trip', 'DRV-103', 'Diesel', 95, 72, 36120, 'Healthy', '2026-09-28', '2026-06-20', 'In Transit: Manila → Baguio', 'OR/CR Valid until 2027-01-18', 'Pioneer Special Risk - Exp 2026-12-15', 'CPC No. 2023-45601', 165, 36120, '6.4 km/L', '₱16.40/km'),
('VEH-004', 'WOD-3312', 'VIP SUV',        'Ford',     'Everest Titanium 4x4', 2024, 7, 'Assigned', 'DRV-104', 'Diesel', 80, 95, 14200, 'Healthy', '2026-11-15', '2026-08-01', 'Terminal A - VIP Lounge', 'OR/CR Valid until 2027-06-30', 'Malayan VIP Coverage - Exp 2027-06-01', 'CPC No. 2024-99812', 98, 14200, '10.5 km/L', '₱11.20/km'),
('VEH-005', 'NBQ-1108', 'Tour Bus',       'Scania',   'Touring HD 49s', 2022, 49, 'Maintenance', NULL, 'Diesel', 300, 40, 78900, 'Under Repair (Brake Pad & Sensor Replacement)', '2026-08-16 (Ongoing)', '2026-05-12', 'Service Center Bay 2', 'OR/CR Valid until 2026-11-20', 'QBE Heavy Fleet - Exp 2026-11-01', 'CPC No. 2022-77123', 310, 78900, '3.5 km/L', '₱24.10/km'),
('VEH-006', 'CBC-8823', 'Executive Van',  'Hyundai',  'Staria Premium 9s', 2023, 9, 'Available', 'DRV-106', 'Diesel', 75, 80, 21500, 'Healthy', '2026-10-14', '2026-07-18', 'Central Depot - Bay 8', 'OR/CR Valid until 2027-03-05', 'Alpha Insurance - Exp 2027-02-28', 'CPC No. 2023-33901', 145, 21500, '11.0 km/L', '₱10.90/km'),
('VEH-007', 'ZAA-5591', 'Executive Van',  'Toyota',   'HiAce Commuter Deluxe', 2023, 15, 'Available', 'DRV-107', 'Diesel', 70, 90, 31200, 'Healthy', '2026-09-22', '2026-06-25', 'Central Depot - Bay 11', 'OR/CR Valid until 2027-05-12', 'FPG Insurance - Exp 2027-04-30', 'CPC No. 2023-11928', 205, 31200, '9.5 km/L', '₱12.30/km'),
('VEH-008', 'UAD-9043', 'Tour Bus',       'Volvo',    'B8R Coach 50s', 2023, 50, 'On Trip', 'DRV-108', 'Diesel', 280, 55, 51200, 'Healthy', '2026-09-30', '2026-07-02', 'In Transit: Clark → Subic Freeport', 'OR/CR Valid until 2027-08-19', 'QBE Heavy Fleet - Exp 2027-07-15', 'CPC No. 2023-66710', 198, 51200, '3.7 km/L', '₱23.20/km');

INSERT INTO vehicles (id, plate_number, type, brand, model, year, capacity, status,
  assigned_driver_id, fuel_type, fuel_capacity, current_fuel, odometer, maintenance_status,
  next_maintenance, last_maintenance, location, reg_document, insurance_document, ltfrb_permit,
  total_trips, total_km, avg_fuel_km, operating_cost_km) VALUES
('VEH-009', 'TGT-1201', 'Tour Bus',      'Yutong',   'ZK6122H9 Coach', 2022, 49, 'Available', 'DRV-105', 'Diesel', 300, 82, 60120, 'Healthy', '2026-10-08', '2026-07-15', 'Central Depot - Bay 1', 'OR/CR Valid until 2027-03-11', 'QBE Heavy Fleet - Exp 2026-12-30', 'CPC No. 2023-22109', 176, 60120, '3.6 km/L', '₱23.80/km'),
('VEH-010', 'KJS-2210', 'Coaster Bus',   'Toyota',   'Coaster Commuter', 2022, 29, 'Available', 'DRV-109', 'Diesel', 95, 78, 42110, 'Healthy', '2026-11-02', '2026-08-05', 'Central Depot - Bay 3', 'OR/CR Valid until 2027-01-22', 'Pioneer Charter - Exp 2027-01-05', 'CPC No. 2023-55820', 152, 42110, '6.6 km/L', '₱15.90/km'),
('VEH-011', 'MBK-3302', 'Executive Van', 'Toyota',   'HiAce Grandia', 2022, 14, 'Available', 'DRV-110', 'Diesel', 70, 74, 31200, 'Healthy', '2026-10-21', '2026-07-28', 'Central Depot - Bay 5', 'OR/CR Valid until 2027-02-08', 'Standard Charter - Exp 2027-01-20', 'CPC No. 2023-66431', 198, 31200, '9.0 km/L', '₱12.60/km'),
('VEH-012', 'ZPL-4410', 'VIP SUV',       'Nissan',   'Terra VL 4x4', 2023, 7, 'Available', 'DRV-111', 'Diesel', 80, 91, 18800, 'Healthy', '2026-12-01', '2026-08-10', 'Terminal B - Executive Bay', 'OR/CR Valid until 2027-07-12', 'Malayan VIP - Exp 2027-06-15', 'CPC No. 2024-22108', 87, 18800, '10.8 km/L', '₱10.90/km'),
('VEH-013', 'QWE-5512', 'Tour Bus',      'King Long', 'XMQ6127 Coach', 2021, 48, 'Available', NULL, 'Diesel', 290, 70, 70230, 'Healthy', '2026-09-30', '2026-06-30', 'Central Depot - Bay 6', 'OR/CR Valid until 2026-12-18', 'QBE Heavy Fleet - Exp 2026-12-01', 'CPC No. 2022-33402', 201, 70230, '3.7 km/L', '₱23.40/km'),
('VEH-014', 'HJK-6619', 'Coaster Bus',   'Hyundai',  'County Deluxe', 2022, 29, 'Available', NULL, 'Diesel', 95, 76, 33120, 'Healthy', '2026-10-11', '2026-07-22', 'Central Depot - Bay 7', 'OR/CR Valid until 2027-04-03', 'Pioneer Charter - Exp 2027-03-10', 'CPC No. 2023-77812', 141, 33120, '6.5 km/L', '₱16.10/km'),
('VEH-015', 'RTY-7720', 'Executive Van', 'Kia',      'Grand Carnival', 2023, 14, 'Available', NULL, 'Diesel', 70, 85, 24110, 'Healthy', '2026-11-19', '2026-08-14', 'Central Depot - Bay 9', 'OR/CR Valid until 2027-05-20', 'Alpha Insurance - Exp 2027-04-25', 'CPC No. 2023-91220', 162, 24110, '9.4 km/L', '₱12.10/km'),
('VEH-016', 'UIO-8821', 'Tour Bus',      'Hino',     'RM2P Grand', 2022, 47, 'Available', NULL, 'Diesel', 260, 68, 55200, 'Healthy', '2026-10-25', '2026-07-30', 'Central Depot - Bay 10', 'OR/CR Valid until 2027-02-27', 'QBE Heavy Fleet - Exp 2027-02-10', 'CPC No. 2023-44105', 188, 55200, '3.9 km/L', '₱22.90/km'),
('VEH-017', 'ASD-9913', 'Coaster Bus',   'Toyota',   'Coaster Deluxe X', 2023, 29, 'Available', NULL, 'Diesel', 95, 88, 28750, 'Healthy', '2026-11-08', '2026-08-08', 'Central Depot - Bay 12', 'OR/CR Valid until 2027-06-01', 'Pioneer Charter - Exp 2027-05-15', 'CPC No. 2023-33870', 137, 28750, '6.7 km/L', '₱15.80/km'),
('VEH-018', 'FGH-1042', 'Executive Van', 'Toyota',   'HiAce Tourer', 2022, 14, 'Available', NULL, 'Diesel', 70, 79, 30110, 'Healthy', '2026-10-30', '2026-07-25', 'Central Depot - Bay 13', 'OR/CR Valid until 2027-03-19', 'Standard Charter - Exp 2027-03-01', 'CPC No. 2023-55690', 153, 30110, '9.1 km/L', '₱12.40/km'),
('VEH-019', 'JKL-2145', 'VIP SUV',       'Toyota',   'Land Cruiser Prado', 2023, 7, 'Available', NULL, 'Diesel', 87, 93, 15220, 'Healthy', '2026-12-15', '2026-08-12', 'Terminal A - VIP Lounge', 'OR/CR Valid until 2027-08-22', 'Malayan VIP - Exp 2027-08-01', 'CPC No. 2024-66102', 76, 15220, '9.8 km/L', '₱11.70/km'),
('VEH-020', 'ZXC-3256', 'Tour Bus',      'Scania',   'Touring HD 45s', 2021, 45, 'On Trip', 'DRV-112', 'Diesel', 290, 52, 67100, 'Healthy', '2026-09-20', '2026-06-28', 'In Transit: Manila → Baguio', 'OR/CR Valid until 2026-11-12', 'QBE Heavy Fleet - Exp 2026-11-01', 'CPC No. 2022-11023', 214, 67100, '3.6 km/L', '₱23.60/km'),
('VEH-021', 'BNM-4367', 'Coaster Bus',   'Toyota',   'Coaster Deluxe', 2022, 29, 'On Trip', 'DRV-113', 'Diesel', 95, 61, 41220, 'Healthy', '2026-10-05', '2026-07-12', 'In Transit: Clark → Subic', 'OR/CR Valid until 2027-01-30', 'Pioneer Charter - Exp 2026-12-20', 'CPC No. 2023-88214', 169, 41220, '6.3 km/L', '₱16.30/km'),
('VEH-022', 'VBN-5478', 'Executive Van', 'Hyundai',  'Staria Premium', 2023, 9, 'On Trip', 'DRV-114', 'Diesel', 75, 58, 22400, 'Healthy', '2026-11-11', '2026-08-02', 'In Transit: NAIA → Tagaytay', 'OR/CR Valid until 2027-04-27', 'Alpha Insurance - Exp 2027-04-10', 'CPC No. 2023-77105', 138, 22400, '10.9 km/L', '₱11.00/km'),
('VEH-023', 'MNB-6589', 'Tour Bus',      'Volvo',    'B8R Coach', 2022, 50, 'On Trip', 'DRV-115', 'Diesel', 280, 48, 58230, 'Healthy', '2026-09-25', '2026-07-08', 'In Transit: Manila → Vigan', 'OR/CR Valid until 2027-02-11', 'QBE Heavy Fleet - Exp 2027-01-25', 'CPC No. 2023-55014', 187, 58230, '3.7 km/L', '₱23.20/km'),
('VEH-024', 'POI-7690', 'Executive Van', 'Toyota',   'HiAce Commuter', 2022, 15, 'On Trip', 'DRV-116', 'Diesel', 70, 62, 34210, 'Healthy', '2026-10-18', '2026-07-20', 'In Transit: BGC → Batangas', 'OR/CR Valid until 2027-03-25', 'Standard Charter - Exp 2027-03-08', 'CPC No. 2023-99210', 172, 34210, '9.2 km/L', '₱12.20/km'),
('VEH-025', 'LKO-8710', 'Coaster Bus',   'Isuzu',    'NPR Coaster', 2021, 28, 'On Trip', 'DRV-117', 'Diesel', 90, 55, 45230, 'Healthy', '2026-11-01', '2026-08-03', 'In Transit: QC → Subic', 'OR/CR Valid until 2026-12-28', 'Pioneer Charter - Exp 2026-12-12', 'CPC No. 2022-66708', 148, 45230, '6.1 km/L', '₱16.60/km'),
('VEH-026', 'IJU-9821', 'Executive Van', 'Mercedes', 'Vito Tourer', 2024, 8, 'Assigned', 'DRV-118', 'Diesel', 66, 90, 9800, 'Healthy', '2026-12-20', '2026-08-15', 'Central Depot - Bay 14', 'OR/CR Valid until 2027-09-01', 'Alpha Insurance - Exp 2027-08-20', 'CPC No. 2024-11230', 64, 9800, '10.2 km/L', '₱11.90/km'),
('VEH-027', 'YTR-0932', 'Tour Bus',      'Hino',     'Grand View 49s', 2021, 49, 'Maintenance', NULL, 'Diesel', 300, 35, 84120, 'Under Repair (Transmission Inspection)', '2026-08-18 (Ongoing)', '2026-05-28', 'Service Center Bay 1', 'OR/CR Valid until 2026-12-05', 'QBE Heavy Fleet - Exp 2026-11-28', 'CPC No. 2022-44019', 265, 84120, '3.4 km/L', '₱24.50/km'),
('VEH-028', 'EWQ-1043', 'Coaster Bus',   'Toyota',   'Coaster Deluxe', 2022, 29, 'Maintenance', NULL, 'Diesel', 95, 42, 39210, 'Aircon System Service', '2026-08-20 (Scheduled)', '2026-07-01', 'Service Center Bay 3', 'OR/CR Valid until 2027-02-19', 'Pioneer Charter - Exp 2027-02-01', 'CPC No. 2023-88102', 155, 39210, '6.4 km/L', '₱16.20/km');

 
 
 
INSERT INTO reservations (id, client_name, contact_person, contact_phone, passenger_count,
  origin, destination, departure_date, departure_time, return_date, vehicle_requested,
  assigned_vehicle_id, assigned_driver_id, status, trip_type, notes, estimated_cost) VALUES
('RES-2026-1089', 'Summit Global Tech Tours',       'Ma. Elena Roxas', '+63 917 334 9011', 42,
 'Makati Shangri-La Hotel', 'Baguio Country Club', '2026-08-15', '06:00 AM', '2026-08-17',
 'Tour Bus (45-50 pax)', 'VEH-001', 'DRV-101', 'Assigned', 'Multi-Day Tour',
 'Corporate team building. Requires luggage bay setup and PA system.', 38500.00),
('RES-2026-1090', 'Horizon Travel Excursions',      'Carlos Rivera', '+63 920 882 1190', 12,
 'NAIA Terminal 3', 'Tagaytay Taal Vista Hotel', '2026-08-14', '09:30 AM', '2026-08-14',
 'Executive Van (14 pax)', 'VEH-002', 'DRV-102', 'In Transit', 'Day Tour & Transfer',
 'VIP international delegates from Singapore.', 14200.00),
('RES-2026-1091', 'Ateneo Alumni Heritage Group',   'Dr. Patricia Gomez', '+63 918 445 6672', 26,
 'Katipunan QC Depot', 'Vigan Heritage Village, Ilocos Sur', '2026-08-16', '05:00 AM', '2026-08-19',
 'Coaster Bus (29 pax)', 'VEH-003', 'DRV-103', 'Confirmed', 'Educational Heritage Tour',
 'Special stops in San Fernando La Union and Candon City.', 46000.00),
('RES-2026-1092', 'Pacific Rim Executive Aviation', 'Hans Von Berg', '+63 917 119 5500', 4,
 'Solaire Resort Entertainment City', 'Balesin Island Flight Hangar, Pasay', '2026-08-14', '02:00 PM', '2026-08-14',
 'VIP SUV (7 pax)', 'VEH-004', 'DRV-104', 'Dispatched', 'VIP Executive Airport Transfer',
 'C-Level Executive Transfer. Strict punctuality required.', 8500.00),
('RES-2026-1093', 'Sunburst Travel Agency',         'Jenna Villareal', '+63 922 770 1928', 48,
 'Clark Freeport Zone', 'Subic Bay Ocean Adventure', '2026-08-14', '08:00 AM', '2026-08-14',
 'Tour Bus (50 pax)', 'VEH-008', 'DRV-108', 'In Transit', 'School Field Trip',
 'Includes tour coordinator seat and onboard emergency kit.', 26500.00),
('RES-2026-1094', 'Greenfield Eco-Ventures',        'Ronald Yap', '+63 917 990 4411', 14,
 'BGC High Street', 'Masungi Georeserve, Tanay Rizal', '2026-08-15', '05:30 AM', '2026-08-15',
 'Executive Van (15 pax)', NULL, NULL, 'Pending', 'Eco Trekking Tour',
 'Early morning hike tour group. Awaiting vehicle allocation.', 12800.00),
('RES-2026-1095', 'Manila Heritage City Tours',     'Antonio Dela Cruz', '+63 918 220 7745', 45,
 'Manila Hotel (Luneta)', 'Intramuros Heritage District', '2026-08-19', '08:00 AM', '2026-08-19',
 'Tour Bus (45-50 pax)', 'VEH-001', 'DRV-101', 'Confirmed', 'City Heritage Tour',
 'Guided walking tour groups with bag drop at Fort Santiago gate.', 22400.00),
('RES-2026-1096', 'Sunrise Ferry & Island Tours',   'Liza Manaloto', '+63 917 551 9020', 42,
 'Cultural Center Complex (CCP)', 'Corregidor Island Ferry Terminal', '2026-08-12', '06:00 AM', '2026-08-12',
 'Tour Bus (45-50 pax)', 'VEH-001', 'DRV-101', 'Completed', 'Island Gateway Day Tour',
 'Completed — ferry link transfer with luggage bay.', 31800.00);

 
 
 
INSERT INTO trips (id, reservation_id, origin, destination, waypoints, vehicle_id, driver_id,
  passengers, scheduled_departure, actual_departure, estimated_arrival, distance_km, status,
  progress_pct, current_step, fuel_estimate, toll_fee, driver_allowance, total_cost) VALUES
('TRP-8801', 'RES-2026-1090', 'NAIA Terminal 3, Pasay', 'Tagaytay Taal Vista Hotel',
 'SLEX Carmona Exit; Silang Bypass Road', 'VEH-002', 'DRV-102', 12,
 '2026-08-14 09:30:00', '2026-08-14 09:34:00', '2026-08-14 11:20:00', 68.4, 'In Transit',
 62, 'In Transit', '₱1,250.00 (18.5 L)', 385.00, 800.00, 2435.00),
('TRP-8802', 'RES-2026-1093', 'Clark Freeport Zone, Pampanga', 'Subic Bay Ocean Adventure, Zambales',
 'SCTEX Dinalupihan Exit; Tipo Expressway', 'VEH-008', 'DRV-108', 48,
 '2026-08-14 08:00:00', '2026-08-14 08:05:00', '2026-08-14 09:45:00', 76.2, 'In Transit',
 80, 'In Transit', '₱3,800.00 (52.0 L)', 480.00, 1200.00, 5480.00),
('TRP-8803', 'RES-2026-1092', 'Solaire Resort Entertainment City', 'Balesin Island Flight Hangar, Pasay',
 'NAIA Expressway (NAIAX)', 'VEH-004', 'DRV-104', 4,
 '2026-08-14 14:00:00', '2026-08-14 13:45:00', '2026-08-14 14:25:00', 12.8, 'Dispatched',
 25, 'Dispatched', '₱320.00 (4.5 L)', 90.00, 500.00, 910.00);

INSERT INTO trip_timeline (trip_id, title, event_time, completed, active_step, sort_order) VALUES
('TRP-8801', 'Scheduled', '2026-08-13 14:00', 1, 0, 1),
('TRP-8801', 'Vehicle Assigned (CAV-4519)', '2026-08-13 16:30', 1, 0, 2),
('TRP-8801', 'Driver Assigned (R. Ramos)', '2026-08-13 16:35', 1, 0, 3),
('TRP-8801', 'Dispatched from Depot', '2026-08-14 09:00', 1, 0, 4),
('TRP-8801', 'In Transit (En Route to Tagaytay)', '2026-08-14 09:34', 1, 1, 5),
('TRP-8801', 'Completed & Returned', 'Pending Arrival', 0, 0, 6),
('TRP-8802', 'Scheduled', '2026-08-12 11:00', 1, 0, 1),
('TRP-8802', 'Vehicle Assigned (UAD-9043)', '2026-08-13 09:00', 1, 0, 2),
('TRP-8802', 'Driver Assigned (J. Tan)', '2026-08-13 09:15', 1, 0, 3),
('TRP-8802', 'Dispatched from Depot', '2026-08-14 07:30', 1, 0, 4),
('TRP-8802', 'In Transit', '2026-08-14 08:05', 1, 1, 5),
('TRP-8802', 'Completed & Returned', 'Pending Arrival', 0, 0, 6),
('TRP-8803', 'Scheduled', '2026-08-14 10:00', 1, 0, 1),
('TRP-8803', 'Vehicle Assigned (WOD-3312)', '2026-08-14 10:15', 1, 0, 2),
('TRP-8803', 'Driver Assigned (M. Bautista)', '2026-08-14 10:20', 1, 0, 3),
('TRP-8803', 'Dispatched to Pickup Point', '2026-08-14 13:45', 1, 1, 4),
('TRP-8803', 'In Transit', 'Pending Pickup', 0, 0, 5),
('TRP-8803', 'Completed & Returned', 'Pending Arrival', 0, 0, 6);

 
 
 
INSERT INTO maintenance_orders (id, vehicle_id, service_type, priority, scheduled_date, status, estimated_cost, notes) VALUES
('WO-2026-081', 'VEH-005', 'Brake System & Electronic Sensor Replacement', 'Critical', '2026-08-16', 'In Repair', 45000.00, 'Scania Coach - Under Repair in Bay 2. Parts ordered.'),
('WO-2026-082', 'VEH-001', '40,000 km Major PMS, Synthetic Engine Oil & Filter', 'Medium', '2026-09-15', 'Scheduled', 18500.00, 'Hino Tour Bus - Scheduled PMS.'),
('WO-2026-083', 'VEH-007', '4-Wheel Laser Alignment & Tire Rotation', 'Low', '2026-09-22', 'Scheduled', 6200.00, 'HiAce Commuter - Routine alignment.');

 
 
 
INSERT INTO fuel_transactions (id, vehicle_id, driver_id, transaction_date, fuel_type, liters,
  price_per_liter, total_cost, odometer, station, receipt_no, efficiency) VALUES
('FL-2026-0941', 'VEH-001', 'DRV-101', '2026-08-13 18:45:00', 'Diesel Max', 145.50, 58.40, 8497.20, 42350, 'Petron SLEX Northbound Km 36', 'REC-PET-99120', '3.8 km/L'),
('FL-2026-0940', 'VEH-002', 'DRV-102', '2026-08-13 14:10:00', 'Diesel', 48.00, 58.20, 2793.60, 28400, 'Shell Southwoods Biñan', 'REC-SHL-44182', '9.2 km/L'),
('FL-2026-0939', 'VEH-003', 'DRV-103', '2026-08-12 19:30:00', 'Diesel', 72.50, 58.50, 4241.25, 36120, 'Caltex NLEX Marilao', 'REC-CTX-77219', '6.4 km/L'),
('FL-2026-0938', 'VEH-004', 'DRV-104', '2026-08-12 11:20:00', 'Diesel', 55.00, 58.30, 3206.50, 14200, 'Petron BGC 32nd Ave', 'REC-PET-10023', '10.5 km/L'),
('FL-2026-0937', 'VEH-008', 'DRV-108', '2026-08-11 16:50:00', 'Diesel Max', 160.00, 58.40, 9344.00, 51200, 'Total SCTEX Clark North', 'REC-TOT-66190', '3.7 km/L');

 
 
 
INSERT INTO cost_categories (name, amount, pct, color, sort_order) VALUES
('Fuel Consumption', 684200.00, 47.90, '#2F80ED', 1),
('Vehicle Maintenance & Parts', 324500.00, 22.70, '#F2994A', 2),
('Driver Allowances & Per Diem', 245800.00, 17.20, '#27AE60', 3),
('Toll Fees & Parking', 118650.00, 8.30, '#56CCF2', 4),
('Permits, Insurance & Reg', 55500.00, 3.90, '#9CA3AF', 5);

INSERT INTO vehicle_cost_categories (category_name, active_units, monthly_expense, cost_per_km, sort_order) VALUES
('Tour Buses (45-50 pax)', 8, 742000.00, '₱23.10', 1),
('Coaster Buses (29 pax)', 6, 312400.00, '₱16.20', 2),
('Executive Vans (14-15 pax)', 10, 285150.00, '₱11.50', 3),
('VIP SUVs (7 pax)', 4, 89100.00, '₱10.80', 4);

INSERT INTO vehicle_cost_ledger (vehicle_id, plate_number, model, fuel_cost, maintenance_cost, driver_expense, total_cost, sort_order) VALUES
('VEH-001', 'NBO-7821', 'Hino Grand View 45s', 112400.00, 18500.00, 38000.00, 168900.00, 1),
('VEH-002', 'CAV-4519', 'Toyota HiAce Grandia', 42100.00, 6200.00, 26000.00, 74300.00, 2),
('VEH-003', 'NDJ-9920', 'Toyota Coaster Deluxe', 68900.00, 9400.00, 30000.00, 108300.00, 3),
('VEH-004', 'WOD-3312', 'Ford Everest Titanium 4x4', 28800.00, 4100.00, 22000.00, 54900.00, 4),
('VEH-005', 'NBQ-1108', 'Scania Touring HD 49s', 132600.00, 45000.00, 42000.00, 219600.00, 5),
('VEH-006', 'CBC-8823', 'Hyundai Staria Premium 9s', 31500.00, 3800.00, 24000.00, 59300.00, 6),
('VEH-007', 'ZAA-5591', 'Toyota HiAce Commuter Deluxe', 39800.00, 6200.00, 28000.00, 74000.00, 7),
('VEH-008', 'UAD-9043', 'Volvo B8R Coach 50s', 128900.00, 12400.00, 40000.00, 181300.00, 8);

INSERT INTO chart_weekly_trips (day_name, trips_completed, sort_order) VALUES
('Mon', 18, 1), ('Tue', 22, 2), ('Wed', 19, 3), ('Thu', 25, 4),
('Fri', 34, 5), ('Sat', 42, 6), ('Sun', 38, 7);

INSERT INTO chart_fuel_monthly (month_label, expense, sort_order) VALUES
('Mar', 320000.00, 1), ('Apr', 345000.00, 2), ('May', 360000.00, 3),
('Jun', 390000.00, 4), ('Jul', 410000.00, 5), ('Aug', 385420.00, 6);

 
 
 
INSERT INTO route_presets (id, name, origin, origin_lat, origin_lng, destination, dest_lat, dest_lng, passenger_count, recommended_vehicle) VALUES
('ROUTE-PRESET-1', 'Metro Manila to Baguio City (Summer Capital Tour)', 'Central Fleet Terminal, Cubao, Quezon City', 14.620000, 121.053000, 'Baguio Country Club, Baguio City', 16.402300, 120.608000, 45, 'Tour Bus (Hino Grand View 45s)'),
('ROUTE-PRESET-2', 'NAIA Airport to Tagaytay Scenic Ridge', 'NAIA Terminal 3, Pasay City', 14.517600, 121.018900, 'Tagaytay Taal Vista Hotel, Tagaytay City', 14.095000, 120.932000, 14, 'Executive Van (Toyota HiAce Grandia)');

INSERT INTO route_waypoints (preset_id, name, lat, lng, sort_order) VALUES
('ROUTE-PRESET-1', 'NLEX Balintawak Toll Plaza', 14.658000, 120.999000, 1),
('ROUTE-PRESET-1', 'TPLEX Rosario Exit', 16.228000, 120.485000, 2),
('ROUTE-PRESET-1', 'Kennon Road / Marcos Highway Junction', 16.320000, 120.550000, 3),
('ROUTE-PRESET-2', 'NAIAX Express Runway', 14.512000, 121.010000, 1),
('ROUTE-PRESET-2', 'CALAX Santa Rosa / Silang Interchange', 14.240000, 121.010000, 2);

INSERT INTO route_alternatives (preset_id, mode_key, title, distance, duration, fuel_estimate, toll_estimate, total_trip_cost, route_score, reason) VALUES
('ROUTE-PRESET-1', 'balanced', 'AI Recommended: Balanced Expressway & Scenic Safety', '248.5 km', '4 hrs 15 mins', '65.4 L (₱3,819)', '₱910.00', '₱6,529.00', '98 / 100', 'Optimal balance of multi-lane toll expressways (NLEX, SCTEX, TPLEX) bypassing suburban traffic choke points and using Marcos Highway for 30% reduced engine thermal load on buses.'),
('ROUTE-PRESET-1', 'fastest', 'Fastest Express Route', '244.2 km', '3 hrs 55 mins', '72.0 L (₱4,204)', '₱1,050.00', '₱7,054.00', '92 / 100', 'Prioritizes maximum continuous speed via TPLEX Pozorrubio Extension. Higher fuel consumption due to aggressive sustained gradient climbs.'),
('ROUTE-PRESET-1', 'shortest', 'Shortest Distance Route', '232.0 km', '5 hrs 20 mins', '68.2 L (₱3,982)', '₱540.00', '₱6,322.00', '84 / 100', 'Direct McArthur Highway provincial arterial. Heavy municipal stop-and-go delays in Bulacan and Tarlac town centers.'),
('ROUTE-PRESET-1', 'fuelEfficient', 'Eco-Optimized & Fuel Efficient', '250.1 km', '4 hrs 30 mins', '59.8 L (₱3,492)', '₱910.00', '₱6,202.00', '95 / 100', 'Cruising-speed profile optimized for low RPM engine torque bands with gentle gradient approach on Marcos Highway.'),
('ROUTE-PRESET-2', 'balanced', 'AI Recommended: CALAX Fast Corridor', '64.8 km', '1 hr 18 mins', '7.2 L (₱420)', '₱320.00', '₱1,540.00', '99 / 100', 'Seamless transfer via NAIAX, SLEX, and CALAX Silang East exit, avoiding Santa Rosa downtown gridlock.'),
('ROUTE-PRESET-2', 'fastest', 'Fastest Express Route', '66.1 km', '1 hr 12 mins', '8.1 L (₱473)', '₱360.00', '₱1,633.00', '94 / 100', 'Continuous highway driving via full CALAX alignment.'),
('ROUTE-PRESET-2', 'shortest', 'Shortest Distance Route', '58.4 km', '2 hrs 05 mins', '8.9 L (₱520)', '₱0.00', '₱1,320.00', '78 / 100', 'Aguinaldo Highway national road. Severe bottlenecks through Bacoor, Imus, and Dasmariñas.'),
('ROUTE-PRESET-2', 'fuelEfficient', 'Eco-Optimized & Fuel Efficient', '64.8 km', '1 hr 22 mins', '6.8 L (₱397)', '₱320.00', '₱1,517.00', '96 / 100', 'Consistent 80 km/h cruising profile on modern tollways.');

INSERT INTO route_history (log_id, route_title, vehicle, generated_date, selected_mode, variance_accuracy, created_by) VALUES
('LOG-AIR-992', 'Metro Manila to Baguio City (Summer Capital)', 'Hino Bus (NBO-7821)', '2026-08-14 09:12:00', 'Balanced', '98.4% On-Target', 1),
('LOG-AIR-991', 'NAIA Airport to Tagaytay Scenic Ridge', 'HiAce Van (CAV-4519)', '2026-08-13 15:40:00', 'Balanced', '99.1% On-Target', 1);

 
 
 
INSERT INTO notifications (title, body, time_label, type, category, target, is_read) VALUES
('Trip Dispatched', 'Vehicle VEH-004 (Mark Bautista) dispatched for VIP Solaire Transfer.', '10 mins ago', 'info', 'Dispatch', 'dispatch-board', 0),
('AI Route Optimization Complete', 'Optimized route generated for Baguio Summer Capital Tour (98% Score).', '25 mins ago', 'success', 'Trip', 'ai-route-planner', 0),
('Maintenance Work Order', 'VEH-005 entered Service Center Bay 2 for brake overhaul.', '1 hour ago', 'warning', 'Maintenance', 'maintenance', 0),
('Fuel Refill Logged', 'FL-2026-0941 logged by Danilo Santos: 145.5 L (₱8,497.20).', '3 hours ago', 'info', 'Fuel', 'fuel-transactions', 1),
('Driver License Expiring', 'Reynaldo Ramos'' driver''s license is due for renewal in 15 days.', '1 day ago', 'warning', 'Driver', 'drivers', 0),
('Vehicle Inspection Due', 'VEH-002 (CAV-4519) annual roadworthiness inspection is scheduled this week.', '2 days ago', 'info', 'Vehicle', 'vehicles', 0);

 
 
 
INSERT INTO system_settings (setting_key, setting_value, description) VALUES
('system.brand', 'Toursphere', 'Application brand name'),
('system.title', 'Toursphere Fleet & Transportation Management', 'Application display title'),
('system.version', '2.4.0', 'System version'),
('integration.booking_core', 'Connected', 'Travel & Tours Main Booking Core - synchronizes incoming reservation queues'),
('integration.hrms', 'Connected', 'Toursphere HRMS Module - employee records, driver payroll, shift attendance'),
('integration.gps_gateway', 'Active', 'Mapping & GPS Telematics API Gateway - OpenStreetMap & Leaflet vector layer'),
('cost.monthly_total', '1428650.00', 'Monthly total operating cost (PHP)'),
('cost.monthly_budget', '1650000.00', 'Monthly operational budget (PHP)'),
('ai.recommendation_1', 'Route Rationalization Savings|Using Module 6 AI Route Planning saved approximately ₱42,300 in unnecessary diesel idling on NLEX routes.', 'AI cost optimization recommendation #1'),
('ai.recommendation_2', 'Driver Efficiency Reward|Danilo Santos and Mark Bautista achieved >95% fuel score, yielding 8% lower consumption vs fleet baseline.', 'AI cost optimization recommendation #2'),
('ai.recommendation_3', 'Fleet PMS Predictor|Timely preventative maintenance on Grand View Coach avoided estimated ₱90k unplanned gearbox repairs.', 'AI cost optimization recommendation #3');



