 
CREATE TABLE IF NOT EXISTS ai_model_registry (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id VARCHAR(50) NOT NULL UNIQUE,
  version VARCHAR(20) NOT NULL,
  algorithm VARCHAR(80) NOT NULL,
  target_variable VARCHAR(50) NOT NULL,
  training_samples INTEGER NOT NULL DEFAULT 0,
  validation_samples INTEGER NOT NULL DEFAULT 0,
  mae DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
  rmse DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
  r2_score DECIMAL(6,4) NOT NULL DEFAULT 0.0000,
  feature_list_json TEXT NOT NULL,
  hyperparameters_json TEXT,
  weights_json TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ColdStart' CHECK (status IN ('ColdStart','Experimental','Validated','Deployed','Deprecated')),
  deployed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_mdl_status ON ai_model_registry(status);
CREATE INDEX IF NOT EXISTS idx_mdl_version ON ai_model_registry(version);

CREATE TABLE IF NOT EXISTS ai_route_candidates_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_id VARCHAR(30) NOT NULL,
  candidate_index INTEGER NOT NULL DEFAULT 0,
  summary_title VARCHAR(200) NOT NULL,
  distance_km DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  duration_mins INTEGER NOT NULL DEFAULT 0,
  traffic_duration_mins INTEGER NOT NULL DEFAULT 0,
  estimated_fuel_l DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  toll_cost_est DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  composite_score INTEGER NOT NULL DEFAULT 0,
  is_selected SMALLINT NOT NULL DEFAULT 0 CHECK (is_selected IN (0,1)),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cand_log ON ai_route_candidates_log(log_id);

ALTER TABLE route_history ADD COLUMN IF NOT EXISTS model_version VARCHAR(30) DEFAULT 'v0-kinematic';
ALTER TABLE route_history ADD COLUMN IF NOT EXISTS predicted_duration_mins INTEGER;
ALTER TABLE route_history ADD COLUMN IF NOT EXISTS predicted_fuel_liters DECIMAL(7,2);
ALTER TABLE route_history ADD COLUMN IF NOT EXISTS actual_duration_mins INTEGER;
ALTER TABLE route_history ADD COLUMN IF NOT EXISTS actual_fuel_liters DECIMAL(7,2);
ALTER TABLE route_history ADD COLUMN IF NOT EXISTS variance_pct DECIMAL(5,2);
ALTER TABLE route_history ADD COLUMN IF NOT EXISTS vehicle_id VARCHAR(20);
ALTER TABLE route_history ADD COLUMN IF NOT EXISTS pre_trip_features_json TEXT;
